---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: 您可以通过从云提供商处购买按需购买或年度市场订阅或从NetApp购买自带许可证来许可BlueXP备份和恢复。要在工作环境中激活BlueXP备份和恢复、为生产数据创建备份以及将备份数据还原到生产系统、需要有效的许可证。 
---
= 为BlueXP备份和恢复设置许可
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以通过从云提供商购买按需购买(PAYGO)或按年在市场上订阅* NetApp智能服务*来许可BlueXP  备份和恢复、也可以从NetApp购买自带许可证(BYOL)来获得许可。要在工作环境中激活BlueXP备份和恢复、为生产数据创建备份以及将备份数据还原到生产系统、需要有效的许可证。

在阅读其他内容之前，请先阅读一些注释：

* 如果您已在云提供商的市场上为Cloud Volumes ONTAP 系统订阅了按需购买(PAYGO)订阅、则您也会自动订阅BlueXP备份和恢复。您无需再次订阅。
* BlueXP  备份和恢复自带许可证(BYOL)是一种浮动许可证、可在与您的BlueXP  组织或帐户关联的所有系统上使用。因此、如果现有BYOL许可证提供了足够的备份容量、则无需再购买一个BYOL许可证。
* 如果您使用的是BYOL许可证、建议同时订阅PAYGO订阅。如果备份的数据超出BYOL许可证的允许范围、或者许可证期限到期、则备份将通过按需购买订阅继续进行、而不会造成服务中断。
* 将内部 ONTAP 数据备份到 StorageGRID 时，您需要 BYOL 许可证，但云提供商存储空间不需要任何成本。


link:concept-backup-to-cloud.html["详细了解与使用BlueXP备份和恢复相关的成本。"]



== 30 天免费试用

如果您在云提供商的市场上注册"按需购买"订阅* NetApp智能服务*、则可以获得BlueXP  备份和恢复30天免费试用版。免费试用将在您订阅市场列表时开始。请注意、如果您在部署Cloud Volumes ONTAP系统时支付市场订阅费用、然后在10天后开始BlueXP备份和恢复免费试用、则您还可以在20天内使用免费试用。

免费试用结束后、您将自动切换到PAYGO订阅、不会中断。如果您决定不再继续使用BlueXP backup and recovery，只需link:prev-ontap-backup-manage.html["从工作环境中取消注册BlueXP备份和恢复"]在试用期结束前，您将不会被收费。



=== 结束免费试用

如果您想在免费试用结束后继续使用BlueXP backup and recovery，则必须设置付费订阅。您可以从BlueXP界面导航到计费部分并选择适合您需求的订阅计划来执行此操作。如果您不想继续使用BlueXP backup and recovery，您可以结束免费试用。

当您结束免费试用而未订阅付费计划时，您的数据将在免费试用结束后 60 天自动删除。您可以选择让系统立即删除您的数据。

.步骤
. 从BlueXP backup and recovery登录页面，选择 *查看免费试用版*。
. 选择*结束免费试用*。
. 选择“免费试用结束后立即删除数据”以立即删除您的数据。
. 在框中输入*结束试用*。
. 选择*结束*进行确认。




== 使用BlueXP备份和恢复PAYGO订阅

对于按需购买、您需要通过一个订阅按小时为云提供商支付对象存储成本和NetApp备份许可成本。即使您有免费试用版或自带许可证(BYOL)，您也应在市场中订阅* NetApp智能服务*：

* 订阅可确保在免费试用结束后不会中断服务。试用结束后、系统将根据您备份的数据量按小时向您收费。
* 如果备份的数据超过BYOL许可证允许的数量、则数据备份和还原操作将通过按需购买订阅继续进行。例如，如果您拥有 10 TiB BYOL 许可证，则 10 TiB 以上的所有容量均通过 PAYGO 订阅付费。


在免费试用期间、或者如果您未超过BYOL许可证、则不会从按需购买订阅中向您收费。

有几个PAYGO BlueXP备份和恢复计划：

* 一个"云备份"软件包、可用于备份Cloud Volumes ONTAP 数据和内部ONTAP 数据。
* 一个"CVO专业版"软件包、可用于捆绑Cloud Volumes ONTAP 和BlueXP备份和恢复。这包括使用许可证为Cloud Volumes ONTAP 系统备份的数量不限(备份容量不计入许可容量)。此选项不支持备份内部ONTAP 数据。
+
请注意、此选项还需要订阅备份和恢复PAYGO、但符合条件的Cloud Volumes ONTAP系统不会产生任何费用。



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["详细了解这些基于容量的许可证包"]。

使用以下链接从云提供商市场订阅BlueXP备份和恢复：

ifdef::aws[]

* AWS：  https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["有关定价详细信息、请访问NetApp智能服务的市场产品"^] .endif::aws[]


ifdef::azure[]

* Azure：  https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["有关定价详细信息、请访问NetApp智能服务的市场产品"^] .endif::azure[]


ifdef::gcp[]

* 谷歌云：  https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["有关定价详细信息、请访问NetApp智能服务的市场产品"^] .endif::gcp[]




== 使用年度合同

每年购买一份年度合同、为BlueXP备份和恢复支付费用。它们提供1年、2年或3年期服务。

如果您从某个市场签有年度合同、则所有BlueXP备份和恢复使用量将从该合同中扣除。您不能将年度市场合同与BYOL混合搭配使用。

ifdef::aws[]

当您使用 AWS 时，有两种年度合同可供选择 https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWS Marketplace 页面"^]对于Cloud Volumes ONTAP和本地ONTAP系统：

* 一种 " 云备份 " 计划，可用于备份 Cloud Volumes ONTAP 数据和内部 ONTAP 数据。
+
如果要使用此选项，请从 Marketplace 页面设置您的订阅，然后再执行 https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["将订阅与您的 AWS 凭据关联"^]。请注意、您还需要使用此年度合同订阅为Cloud Volumes ONTAP 系统付费、因为在BlueXP中、您只能为AWS凭据分配一个有效订阅。

* 一种"CVO专业人员"计划、可用于捆绑Cloud Volumes ONTAP 和BlueXP备份和恢复。这包括使用许可证为Cloud Volumes ONTAP 系统备份的数量不限(备份容量不计入许可容量)。此选项不支持备份内部ONTAP 数据。
+
请参见 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 许可主题"^] 了解有关此许可选项的更多信息。

+
如果您想使用此选项，您可以在创建Cloud Volumes ONTAP工作环境时设置年度合同，然后BlueXP会提示您订阅 AWS Marketplace。endif::aws[]



ifdef::azure[]

使用 Azure 时，有两份年度合同可供选择 https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Azure Marketplace页面"^]对于Cloud Volumes ONTAP和本地ONTAP系统：

* 一种 " 云备份 " 计划，可用于备份 Cloud Volumes ONTAP 数据和内部 ONTAP 数据。
+
如果要使用此选项，请从 Marketplace 页面设置您的订阅，然后再执行 https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html#subscribe["将订阅与您的Azure凭据关联起来"^]。请注意、您还需要使用此年度合同订阅为Cloud Volumes ONTAP系统付费、因为在BlueXP中、您只能为Azure凭据分配一个有效订阅。

* 一种"CVO专业人员"计划、可用于捆绑Cloud Volumes ONTAP 和BlueXP备份和恢复。这包括使用许可证为Cloud Volumes ONTAP 系统备份的数量不限(备份容量不计入许可容量)。此选项不支持备份内部ONTAP 数据。
+
请参见 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 许可主题"^] 了解有关此许可选项的更多信息。

+
如果您想使用此选项，您可以在创建Cloud Volumes ONTAP工作环境时设置年度合同，然后BlueXP会提示您订阅 Azure 市场。endif::azure[]



ifdef::gcp[]

当您使用 GCP 时，请联系您的NetApp销售代表购买年度合同。此合同在Google Cloud Marketplace中以私人优惠形式提供。

NetApp与您分享私人优惠后，您可以在BlueXP backup and recovery激活期间从 Google Cloud Marketplace 订阅时选择年度计划。endif::gcp[]



== 使用BlueXP备份和恢复BYOL许可证

NetApp 自带许可证的期限为 1 年， 2 年或 3 年。您只需为所保护的数据付费，此费用由要备份的源 ONTAP 卷的逻辑已用容量（ _before_any 的效率）计算得出。此容量也称为前端 TB （前端 TB ）。

BYOL BlueXP  备份和恢复许可证是一种浮动许可证、其中总容量在与您的BlueXP  组织或帐户关联的所有系统之间共享。对于ONTAP系统、您可以通过对计划备份的卷运行命令行界面命令来大致估算所需的容量 `volume show -fields logical-used-by-afs`。

如果您没有BlueXP备份和恢复BYOL许可证、请单击BlueXP右下角的聊天图标购买一个。

或者、如果您有一个不会使用的未分配的基于节点的Cloud Volumes ONTAP 许可证、则可以将其转换为具有相同美元等价性和相同到期日期的BlueXP备份和恢复许可证。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["有关详细信息，请访问此处"^]。

您可以使用BlueXP电子钱包管理BYOL许可证。您可以通过BlueXP电子钱包添加新许可证、更新现有许可证以及查看许可证状态。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["了解如何使用电子钱包添加许可证"^](英文)
