---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: 在使用BlueXP backup and recovery之前，请执行几个步骤来设置备份目标。 
---
= 在使用BlueXP backup and recovery之前设置备份目标
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在使用BlueXP backup and recovery之前，请执行几个步骤来设置备份目标。

开始之前、请查看link:concept-start-prereq.html["前提条件"]以确保您的环境已准备就绪。



== 准备备份目标

准备以下一个或多个备份目标：

* NetAppStorageGRID。
+
请参阅 https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["了解StorageGRID"^]。

+
参考 https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID 文档"^]有关StorageGRID的详细信息。

* 亚马逊网络服务。请参阅 https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Amazon S3 文档"^]。
+
执行以下操作以准备将 AWS 作为备份目标：

+
** 在AWS中设置帐户。
** 在 AWS 中配置 S3 权限，列于下一节中。
** 有关在BlueXP  中管理AWS存储的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["管理Amazon S3存储分段"^]。




* 微软 Azure。
+
** 请参阅 https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Azure NetApp Files 文档"^]。
** 在Azure中设置帐户。
** 配置 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure权限"^]在 Azure 中。
** 有关在BlueXP中管理 Azure 存储的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["管理Azure存储帐户"^] 。




在备份目标本身中配置选项后，您稍后可以在BlueXP backup and recovery服务中将其配置为备份目标。有关如何在BlueXP backup and recovery中配置备份目标的详细信息，请参阅link:br-start-discover-backup-targets.html["发现备份目标"] 。



== 设置 S3 权限

您需要配置两组 AWS S3 权限：

* Connector创建和管理S3存储分段的权限。
* 内部 ONTAP 集群的权限，以便可以将数据读写到 S3 存储分段。


.步骤
. 确保连接器具有所需的权限。有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["BlueXP  策略权限"]。
+

NOTE: 在AWS中国地区创建备份时、您需要将IAM策略中所有_Resource_部分下的AWS资源名称"arn"从"aws"更改为"AAWS CN"；例如 `arn:aws-cn:s3:::netapp-backup-*`。

. 激活此服务后、备份向导将提示您输入访问密钥和机密密钥。这些凭据将传递到 ONTAP 集群，以便 ONTAP 可以将数据备份和还原到 S3 存储分段。为此，您需要创建具有以下权限的 IAM 用户。
+
请参见 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS 文档：创建角色以向 IAM 用户委派权限"^]。

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

