---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp BlueXP backup and recovery保护您的 VMware 工作负载。 
---
= 使用BlueXP backup and recovery概述保护 VMware 工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用BlueXP backup and recovery保护您的 VMware VM 和数据存储。 BlueXP backup and recovery提供快速、节省空间、崩溃一致和 VM 一致的备份和恢复操作。您可以将 VMware 工作负载备份到 Amazon Web Services S3 或StorageGRID ，并将 VMware 工作负载恢复到本地 VMware 主机。


NOTE: 此版本的BlueXP backup and recovery仅支持 VMware vCenter，并且无法发现vVols或vVols上的 VM。

使用BlueXP backup and recovery来实施 3-2-1 策略，其中您在 2 个不同的存储系统上拥有 3 个源数据副本，并在云中拥有 1 个副本。  3-2-1 方法的优点包括：

* 多个数据副本可提供多层保护、抵御内部(内部)和外部网络安全威胁。
* 多种介质类型可确保在一种介质类型发生物理或逻辑故障时能够进行故障转移。
* 现场副本有助于快速恢复，而异地副本则可在现场副本受损时使用。


[]
====
*注意* 要切换到BlueXP backup and recoveryUI 版本，请参阅link:br-start-switch-ui.html["切换到以前的BlueXP backup and recoveryUI"] 。

====
您可以使用BlueXP backup and recovery来执行与 VMware 工作负载相关的以下任务：

* link:br-use-vmware-discovery.html["发现 VMware 工作负载"]
* link:br-use-vmware-protection-groups.html["为 VMware 工作负载创建和管理保护组"]
* link:br-use-vmware-backup.html["备份 VMware 工作负载"]
* link:br-use-vmware-restore.html["恢复 VMware 工作负载"]

