---
sidebar: sidebar 
permalink: concept-clone-cloud-native-oracle-concepts.html 
keywords: cloud-native application data, clone, Cloud Manager, BlueXP, Oracle database, Oracle, clone limitations, clone methods, clone naming scheme, requirements, clone specification file 
summary: 在克隆数据库之前了解克隆概念。 
---
= 克隆概念和要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用数据库备份将Oracle数据库克隆到源数据库主机或备用主机。您可以从主存储系统克隆备份。

克隆数据库之前、您应了解克隆概念并确保满足所有要求。



== 克隆 Oracle 数据库的要求

克隆 Oracle 数据库之前，您应确保满足前提条件。

* 您应已创建数据库的备份。要成功执行克隆操作、您应已成功创建联机数据和日志备份。
* 在asm_diskstring参数中、您应配置：
+
** AFD：*(如果使用的是ASMFD)
** ORCL：*如果您使用的是ASMLIB
** /dev/ASMUDEV (如果使用的是<exact_device_location>)


* 如果要在备用主机上创建克隆，则备用主机应满足以下要求：
+
** 此插件应安装在备用主机上。
** Oracle软件应安装在备用主机上。
** 如果要克隆iSCSI SAN存储上的数据库、则克隆主机应能够从存储中发现LUN。如果要克隆到备用主机、请确保在存储和备用主机之间建立iSCSI会话。
** 如果源数据库是 ASM 数据库：
+
*** ASM 实例应在要执行克隆的主机上启动并运行。
*** 如果要将克隆数据库的归档日志文件放置在专用ASM磁盘组中、应在克隆操作之前配置ASM磁盘组。
*** 可以配置数据磁盘组的名称、但请确保要执行克隆的主机上的任何其他ASM磁盘组不使用该名称。
*** 驻留在ASM磁盘组上的数据文件会在克隆工作流中进行配置。








== 限制

* 不支持克隆qtree上的数据库。
* 不支持备份克隆的数据库。




== 克隆方法

您可以使用基本方法或克隆规范文件创建克隆。



=== 使用基本方法克隆

您可以根据源数据库和选定备份使用默认配置创建克隆。

* 数据库参数、主数据库和操作系统用户默认为源数据库。
* 数据文件路径根据选定的命名方案进行命名。
* 无法指定脚本前、脚本后和SQL语句。
* 默认情况下、恢复选项为*直到取消*、它会使用与数据备份关联的日志备份进行恢复




=== 使用规范文件克隆

您可以在克隆规范文件中定义配置、并使用它克隆数据库。您可以下载规范文件、根据需要对其进行修改、然后上传该文件。 link:task-clone-cloud-native-oracle-data.html["了解更多信息。"]。

规范文件中定义的可修改的不同参数如下：

|===
| 参数 | Description 


 a| 
control_files
 a| 
克隆数据库的控制文件的位置。

控制文件的数量将与源数据库相同。如果要覆盖控制文件路径，可以提供其他控制文件路径。主机上应存在文件系统或ASM磁盘组。



 a| 
redo日志
 a| 
重做日志的位置、大小、重做组数量。

克隆数据库至少需要两个重做日志组。如果要覆盖重做日志文件路径、可以将重做日志文件路径自定义为与源数据库不同的文件系统。主机上应存在文件系统或ASM磁盘组。



 a| 
ORACLE_VERSION
 a| 
目标主机上的Oracle版本。



 a| 
ORACLE_HOME
 a| 
目标主机上的Oracle主目录。



 a| 
enable_archive_log_mode
 a| 
控制克隆数据库的归档日志模式



 a| 
数据库参数
 a| 
克隆数据库的数据库参数



 a| 
SQL_语句
 a| 
克隆后要在数据库上执行的SQL语句



 a| 
os_user_detail
 a| 
目标克隆数据库上的Oracle OS用户



 a| 
数据库端口
 a| 
如果主机上禁用了操作系统身份验证、则用于与数据库通信的端口。



 a| 
asm_port
 a| 
如果在create clone输入中提供了凭据、则用于与ASM数据库进行通信的端口。



 a| 
skip_recovery
 a| 
不执行恢复操作。



 a| 
直到_scn
 a| 
将数据库恢复到指定的系统更改号(SCN)。



 a| 
截止时间
 a| 
将数据库恢复到指定的日期和时间。

接受的格式为_MM/dd/yyyy hh：mm：ss_。



 a| 
Until_cancel
 a| 
通过挂载与选择进行克隆的数据备份关联的日志备份来恢复。

克隆的数据库将恢复到丢失或损坏的日志文件为止。



 a| 
log_paths
 a| 
用于恢复克隆数据库的归档日志路径的其他位置。



 a| 
源位置
 a| 
磁盘组或挂载点在源数据库主机上的位置。



 a| 
clone_location
 a| 
需要在与源位置对应的目标主机上创建的磁盘组或挂载点的位置。



 a| 
location_type
 a| 
它可以是asm_diskgroup或mountpoint。

这些值会在下载文件时自动填充。您不应编辑此参数。



 a| 
pre_script
 a| 
要在创建克隆之前在目标主机上执行的脚本。



 a| 
post_script
 a| 
创建克隆后要在目标主机上执行的脚本。



 a| 
path
 a| 
克隆主机上脚本的绝对路径。

您应将此脚本存储在此路径中的/var/opt/snapcenter/spl/scripts或任何文件夹中。



 a| 
超时
 a| 
为目标主机上运行的脚本指定的超时时间。



 a| 
参数
 a| 
为脚本指定的参数。

|===


== 克隆命名方案

克隆命名方案定义了挂载点的位置以及克隆数据库的磁盘组的名称。您可以选择*相同*或*自动生成*。



=== 相同的命名方案

如果选择克隆命名方案为*相同*、则挂载点的位置以及克隆数据库的磁盘组的名称将与源数据库相同。

例如、如果源数据库的挂载点为//netapp_sourcedb/data_1、+Data1_DG_、则对于克隆的数据库、SAN上的NFS和ASM的挂载点保持不变。

* 控制文件和重做文件的数量和路径等配置将与源相同。
+

NOTE: 如果重做日志或控制文件路径位于非数据卷上、则用户应已在目标主机中配置ASM磁盘组或挂载点。

* Oracle操作系统用户和Oracle版本将与源数据库相同。
* 克隆存储卷名称的格式如下：sourceVolNameSCS_Clone_CurrentTimeStampNumber。
+
例如、如果源数据库上的卷名称为_sourceVolName_、则克隆的卷名称为_sourceVolNameSCS_Clone_1661420020304608825_。

+

NOTE: CurrentTimeStampNumber_在卷名称中提供了唯一性。





=== 自动生成的命名方案

如果选择*自动生成*克隆方案、则挂载点的位置以及克隆数据库的磁盘组的名称将附加一个后缀。

* 如果选择了基本克隆方法、则后缀为*克隆SID*。
* 如果选择了规范文件方法、则后缀将是下载克隆规范文件时指定的*后缀*。


例如、如果源数据库的挂载点为//netapp_sourcedb/data_1_、而*克隆SID*或*后缀*为_HR_、则克隆数据库的挂载点将为//netapp_sourcedb/data_1_HR_。

* 控制文件和重做日志文件的数量将与源相同。
* 所有重做日志文件和控制文件都位于一个克隆的数据挂载点或数据ASM磁盘组上。
* 克隆存储卷名称的格式如下：sourceVolNameSCS_Clone_CurrentTimeStampNumber。
+
例如、如果源数据库上的卷名称为_sourceVolName_、则克隆的卷名称为_sourceVolNameSCS_Clone_1661420020304608825_。

+

NOTE: CurrentTimeStampNumber_在卷名称中提供了唯一性。

* NAS挂载点的格式为_SourceNASMountPoint_suffix_。
* ASM磁盘组的格式为_SourceDiskgroup_suffix_。
+

NOTE: 如果克隆磁盘组中的字符数大于25、则该磁盘组将具有_SC_Hasclode_suffix_。





== 数据库参数

无论克隆命名方案如何、以下数据库参数的值都将与源数据库的值相同。

* log_archive_format
* 审核跟踪
* 流程
* PGA_aggregate_target
* remote_login_passwordfile
* undo_tablespace
* open_cursors
* sGA目标
* DB_block_size


以下数据库参数的值将根据克隆SID附加一个后缀。

* audit_file_dest =｛sourcedataset_parametervalue｝_suffix
* log_archive_dest_1 =｛sourcedataset_ORACLEHME｝_suffix




== 克隆特定的预处理程序和后处理程序支持的预定义环境变量

在克隆数据库时执行预处理和后处理脚本时、您可以使用受支持的预定义环境变量。

* sc_original_SID指定源数据库的SID。将为应用程序卷填充此参数。示例： NFS32
* sc_original_host指定源主机的名称。将为应用程序卷填充此参数。示例： asmrac1.gdl.englab.netapp.com
* sc_oracle_home指定目标数据库的Oracle主目录的路径。示例： /ora01/app/oracle/product/181.0/db_1
* sc_backup_name指定备份的名称。将为应用程序卷填充此参数。示例
+
** 如果数据库未在ARCHIVELOG模式下运行：data@Rg2_scspr2417819002_07-2021_12.16.48.9267_0_LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
** 如果数据库在ARCHIVELOG模式下运行：data@Rg2_scspr2417819002_07-2021_12.16.48.9267_0| log@Rg2_scspr2417819002_07-2021_12.16.9267_1、Rg2_scspr2417819002_07-2021_2021_12.16.267_12.267_SC267_12.202_R202_R4202_12.202_R202_R202_12.202_R48.202_12.202_R202_R202_R202_12.


* sc_original_os_user指定源数据库的操作系统所有者。示例： Oracle
* sc_original_os_Group指定源数据库的操作系统组。示例： oinstall
* sc_target_SID指定克隆数据库的SID。对于 PDB 克隆工作流，不会预定义此参数的值。将为应用程序卷填充此参数。示例： clonedb
* sc_target_host指定要克隆数据库的主机的名称。将为应用程序卷填充此参数。示例： asmrac1.gdl.englab.netapp.com
* sc_target_os_user指定克隆数据库的操作系统所有者。对于 PDB 克隆工作流，不会预定义此参数的值。示例： Oracle
* sc_target_os_Group指定克隆数据库的操作系统组。对于 PDB 克隆工作流，不会预定义此参数的值。示例： oinstall
* sc_target_DB_port指定克隆数据库的数据库端口。对于 PDB 克隆工作流，不会预定义此参数的值。示例： 1521.13




=== 支持的分隔符

* @用于将数据与其数据库名称分隔开、并将值与其密钥分隔开。示例：data@RG2_scspr2417819002_07-2021_12.16.48.9267_0_LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
* 用于在SC_backup_name参数的两个不同实体之间分隔数据。示例：DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 0_LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
* 用于分隔同一个键的一组变量。示例：data@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0_log@RG2_scspr2417819002_07-2021_12.16.48.9267_1、RG2_scspr2417819002_07-21 - 2021_12.16.48.9267_202_2021_SC202_202_202_202_2021_202_12.1648.9267_SC202_202_202_2021_2021_2021_SC202

