---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用NetApp BlueXP backup and recovery保护您的 VMware 工作负载。 
---
= SnapCenter Plug-in for VMware vSphere以用于BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应该在 BlueXP 备份和恢复中注册适用于 VMware vSphere 主机的 SnapCenter 插件，以便显示数据存储区和虚拟机。只有具有管理访问权限的用户才能注册适用于VMware vSphere的SnapCenter 插件主机。

[]
====
*注意* 要切换到BlueXP backup and recovery工作负载，请参阅link:br-start-switch-ui.html["切换到不同的BlueXP backup and recovery工作负载"] 。

====
.步骤
. 在BlueXP UI 中，选择 *保护* > *备份和恢复* > *虚拟机*。
. 从“*设置*”下拉菜单中，选择“SnapCenter Plug-in for VMware vSphere*”。
. 选择“SnapCenter Plug-in for VMware vSphere”*。
. 指定以下详细信息：
+
.. 在适用于VMware vSphere的SnapCenter 插件字段中、指定适用于VMware vSphere的SnapCenter 插件主机的FQDN或IP地址。
.. 在端口字段中、指定运行适用于VMware vSphere的SnapCenter 插件主机的端口号。
+
您应确保在默认8144端口上运行的适用于VMware vSphere的内部SnapCenter 插件主机与在任何云提供商(Amazon Web Services、Microsoft Azure、Google云平台)或内部运行的BlueXP连接器实例之间的通信是开放的。

.. 在用户名和密码字段中、指定具有管理员角色的vCenter用户的凭据。


. 选择 * 注册 * 。


* 完成后 *

选择“*备份和恢复*”>“*虚拟机*”以查看使用已注册的SnapCenter Plug-in for VMware vSphere保护的所有数据存储区和虚拟机。
