---
settings:
  name: Cloud Backup
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: 云提供商
    default: 所有云提供商
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure 酒店
      id: azure
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: Cloud Backup 文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 了解 Cloud Backup
      url: "/concept-backup-to-cloud.html"
    - title: 设置许可
      url: "/task-licensing-cloud-backup.html"
    - title: 监控备份和还原作业的状态
      url: "/task-monitor-backup-jobs.html"
  - title: 备份和还原 ONTAP 数据
    entries:
    - title: 保护 ONTAP 数据
      url: "/concept-ontap-backup-to-cloud.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: 将内部 ONTAP 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: 将内部 ONTAP 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: 将内部 ONTAP 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: 将内部 ONTAP 备份到 StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: 管理 ONTAP 备份
      url: "/task-manage-backups-ontap.html"
    - title: 管理集群级别的备份设置
      url: "/task-manage-backup-settings-ontap.html"
    - title: 从 ONTAP 备份还原
      url: "/task-restore-backups-ontap.html"
  - title: 备份和还原 Kubernetes 数据
    entries:
    - title: 保护您的 Kubernetes 数据
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: 管理 Kubernetes 备份
      url: "/task-manage-backups-kubernetes.html"
    - title: 从 Kubernetes 备份还原
      url: "/task-restore-backups-kubernetes.html"
  - title: 备份和还原应用程序数据
    entries:
    - title: 备份和还原内部应用程序数据
      entries:
      - title: 保护内部应用程序数据
        url: "/concept-protect-app-data-to-cloud.html"
      - title: 注册 SnapCenter 服务器
        url: "/task-register-snapcenter-server.html"
      - title: 创建用于备份应用程序的策略
        url: "/task-create-policies-apps.html"
      - title: 将内部应用程序数据备份到Amazon Web Services
        flavor: aws
        url: "/task-backup-app-data-to-aws.html"
      - title: 将内部应用程序数据备份到Microsoft Azure
        flavor: azure
        url: "/task-backup-app-data-to-azure.html"
      - title: 将内部应用程序数据备份到Google Cloud
        flavor: gcp
        url: "/task-backup-app-data-to-gcp.html"
      - title: 将内部应用程序数据备份到StorageGRID
        url: "/task-backup-app-data-to-storagegrid.html"
      - title: 管理应用程序的保护
        url: "/task-manage-app-backups.html"
      - title: 还原应用程序数据
        entries:
        - title: 还原 Oracle 数据库
          url: "/task-restore-oracle-data.html"
        - title: 还原 SQL Server 数据库
          url: "/task-restore-sql-data.html"
      - title: 挂载应用程序备份
        url: "/task-mount-app-backup.html"
    - title: 备份和还原Cloud原生 应用程序数据
      entries:
      - title: 保护您的Cloud原生 应用程序数据
        url: "/concept-protect-cloud-app-data-to-cloud.html"
      - title: 前提条件
        url: "/reference-prereq-protect-cloud-native-app-data.html"
      - title: 备份Cloud原生 应用程序数据
        entries:
        - title: 发现应用程序
          url: "/task-discover-applications.html"
        - title: 备份Cloud原生 应用程序数据
          url: "/task-backup-cloud-native-app-data.html"
      - title: 管理Cloud原生 应用程序数据的保护
        url: "/task-manage-cloud-native-app-data.html"
      - title: 还原Cloud原生 应用程序数据
        url: "/task-restore-cloud-native-app-data.html"
  - title: 备份和还原虚拟机数据
    entries:
    - title: 保护虚拟机数据
      url: "/concept-protect-vm-data.html"
    - title: 注册适用于VMware vSphere的SnapCenter 插件
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: 创建用于备份虚拟机的策略
      url: "/task-create-policies-vms.html"
    - title: 将数据存储库备份到Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 将数据存储库备份到Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 将数据存储库备份到StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 管理虚拟机的保护
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 还原虚拟机数据
      url: "/task-restore-vm-data.html"
  - title: 使用 REST API 实现自动化
    url: "/api-backup-restore.html"
  - title: 参考
    entries:
    - title: Cloud Backup策略设置
      url: "/concept-cloud-backup-policies.html"
    - title: 支持的 AWS 归档存储层
      url: "/reference-aws-backup-tiers.html"
    - title: 支持的 Azure 归档访问层
      url: "/reference-azure-backup-tiers.html"
    - title: 在 Azure 中配置备份以实现多帐户访问
      url: "/reference-backup-multi-account-azure.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解 Cloud Backup
      url: concept-backup-to-cloud.html
    - title: 新增功能
      url: whats-new.html
    - title: 设置许可
      url: task-licensing-cloud-backup.html
    - title: 监控备份和还原作业的状态
      url: task-monitor-backup-jobs.html
  - title: 将 ONTAP 数据备份到云
    links:
    - title: Cloud Volumes ONTAP 到 Amazon S3
      url: task-backup-to-s3.html
      flavor: aws
    - title: Cloud Volumes ONTAP 到 Azure Blob
      url: task-backup-to-azure.html
      flavor: azure
    - title: Cloud Volumes ONTAP 到 Google Cloud
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: 内部 ONTAP 到 Amazon S3
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: 内部 ONTAP 到 Azure Blob
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: 内部部署 ONTAP 到 Google Cloud
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: 内部部署 ONTAP 到 StorageGRID
      url: task-backup-onprem-private-cloud.html
  - title: 将 Kubernetes 数据备份到云
    links:
    - title: Kubernetes 集群到 Amazon S3
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: Kubernetes 集群到 Azure Blob
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: Kubernetes 集群到 Google Cloud
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: 备份和还原应用程序数据
    links:
    - title: 将内部应用程序数据备份到Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: 将内部应用程序数据备份到Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: 将内部应用程序数据备份到Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: 将内部应用程序数据备份到StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: 将Oracle数据库从云还原到内部
      url: task-restore-oracle-data.html
    - title: 将SQL Server数据库从云还原到内部
      url: task-restore-sql-data.html
    - title: 备份Cloud原生 应用程序数据
      url: task-backup-cloud-native-app-data.html
    - title: 还原Cloud原生 应用程序数据
      url: task-restore-cloud-native-app-data.html
  - title: 备份和还原虚拟机数据
    links:
    - title: 将数据存储库备份到Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 将数据存储库备份到Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 将数据存储库备份到StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 从云还原虚拟机
      url: task-restore-vm-data.html
  - title: 从ONTAP 备份文件还原数据
    links:
    - title: 还原 ONTAP 卷
      url: task-restore-backups-ontap.html
    - title: 从ONTAP 卷还原文件和文件夹
      url: task-restore-backups-ontap.html
    - title: 还原 Kubernetes 卷
      url: task-restore-backups-kubernetes.html
  - title: 管理 ONTAP 备份文件
    links:
    - title: 启用和禁用卷备份
      url: task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes
    - title: 编辑现有备份策略
      url: task-manage-backups-ontap.html#editing-an-existing-backup-policy
    - title: 添加新备份策略
      url: task-manage-backups-ontap.html#adding-a-new-backup-policy
    - title: 更改分配给现有卷的策略
      url: task-manage-backups-ontap.html#changing-the-policy-assigned-to-existing-volumes
    - title: 创建手动卷备份
      url: task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time
    - title: 查看每个卷的备份列表
      url: task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume
    - title: 删除备份
      url: task-manage-backups-ontap.html#deleting-backups
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP博客
      url: https://cloud.netapp.com/blog
    - title: BlueXP用例
      url: https://cloud.netapp.com/cloud-backup
    - title: 云网络研讨会
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文档
