---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: 云提供商
    default: 所有云提供商
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure 酒店
      id: azure
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP备份和恢复文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/reference-limitations.html"
  - title: 入门
    entries:
    - title: 了解有关BlueXP备份和恢复的信息
      url: "/concept-backup-to-cloud.html"
    - title: 设置许可
      url: "/task-licensing-cloud-backup.html"
  - title: 监控数据保护
    entries:
    - title: 关于数据保护覆盖范围的报告
      url: "/task-report-inventory.html"
    - title: 监控备份和还原作业的状态
      url: "/task-monitor-backup-jobs.html"
  - title: 备份和还原 ONTAP 数据
    entries:
    - title: 保护ONTAP 卷数据
      url: "/concept-ontap-backup-to-cloud.html"
    - title: 规划您的保护之旅
      url: "/concept-protection-journey.html"
    - title: 管理ONTAP卷的策略
      url: "/task-create-policies-ontap.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: 将 Cloud Volumes ONTAP 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: 将内部 ONTAP 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: 将内部 ONTAP 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: 将内部 ONTAP 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: 将内部ONTAP备份到ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: 将内部 ONTAP 备份到 StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: 管理 ONTAP 备份
      url: "/task-manage-backups-ontap.html"
    - title: 从 ONTAP 备份还原
      url: "/task-restore-backups-ontap.html"
    - title: 管理集群级别的对象备份设置
      url: "/task-manage-backup-settings-ontap.html"
  - title: 备份和还原内部应用程序数据
    entries:
    - title: 保护内部应用程序数据
      url: "/concept-protect-app-data-to-cloud.html"
    - title: 注册 SnapCenter 服务器
      url: "/task-register-snapcenter-server.html"
    - title: 创建用于备份应用程序的策略
      url: "/task-create-policies-apps.html"
    - title: 将内部应用程序数据备份到Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: 将内部应用程序数据备份到Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: 将内部应用程序数据备份到Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: 将内部应用程序数据备份到StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: 管理应用程序的保护
      url: "/task-manage-app-backups.html"
    - title: 还原内部应用程序数据
      entries:
      - title: 还原 Oracle 数据库
        url: "/task-restore-oracle-data.html"
      - title: 还原 SQL Server 数据库
        url: "/task-restore-sql-data.html"
      - title: 还原SAP HANA数据库
        url: "/task-restore-hana-backup.html"
      - title: 还原MongoDB、MySQL和PostgreSQL数据库
        url: "/task-restore-customplugin-backup.html"
  - title: 备份和还原云原生应用程序数据
    entries:
    - title: 保护云原生应用程序数据
      url: "/concept-protect-cloud-app-data-to-cloud.html"
    - title: 备份云原生Oracle数据库
      entries:
      - title: 快速入门
        url: "/task-quick-start-oracle.html"
      - title: 为ONTAP 配置FSX
        url: "/reference-configure-fsx-for-ontap.html"
      - title: 配置Cloud Volumes ONTAP
        url: "/reference-configure-cloud-volumes-ontap.html"
      - title: 配置 Azure NetApp Files
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: 安装适用于Oracle的SnapCenter 插件并添加数据库主机
        url: "/task-add-host-discover-oracle-databases.html"
      - title: 备份 Oracle 数据库
        url: "/task-backup-cloud-native-oracle-data.html"
    - title: 备份云原生SAP HANA数据库
      entries:
      - title: 快速入门
        flavor: azure
        url: "/task-quick-start-hana.html"
      - title: 配置 Azure NetApp Files
        flavor: azure
        url: "/reference-configure-azure-netapp-files.html"
      - title: 安装适用于SAP HANA的SnapCenter 插件并添加数据库主机
        flavor: azure
        url: "/task-deploy-snapcenter-plugin-for-sap-hana.html"
      - title: 备份 SAP HANA 数据库
        flavor: azure
        url: "/task-backup-cloud-native-sap-hana-data.html"
    - title: 使用REST API备份云原生SQL Server数据库
      entries:
      - title: 快速入门
        url: "/task-quick-start-sql.html"
      - title: 为ONTAP 配置FSX
        url: "/reference-configure-fsx-for-ontap.html"
      - title: 添加主机并安装适用于SQL Server的SnapCenter插件
        url: "/task-add-sqlhost-install-plugin-sql.html"
      - title: 备份 SQL Server 数据库
        url: "/task-backup-cloud-native-sql-data.html"
    - title: 还原云原生Oracle数据库
      entries:
      - title: 还原到原始位置
        url: "/task-restore-cloud-native-oracle-data-to-original-location.html"
      - title: 还原到备用位置
        url: "/task-restore-cloud-native-oracle-data-to-alternate-location.html"
    - title: 还原云原生SAP HANA数据库
      flavor: azure
      url: "/task-restore-cloud-native-sap-hana-data.html"
    - title: 还原云原生SQL Server数据库
      url: "/task-restore-cloud-native-sql-data.html"
    - title: 克隆云原生Oracle数据库
      entries:
      - title: 克隆概念和要求
        url: "/concept-clone-cloud-native-oracle-concepts.html"
      - title: 克隆云原生Oracle数据库
        url: "/task-clone-cloud-native-oracle-data.html"
    - title: 刷新SAP HANA目标系统
      flavor: azure
      url: "/task-refresh-sap-hana-target-system.html"
    - title: 管理云原生应用程序数据的保护
      url: "/task-manage-cloud-native-app-data.html"
  - title: 备份和还原虚拟机数据
    entries:
    - title: 保护虚拟机数据
      url: "/concept-protect-vm-data.html"
    - title: 注册适用于VMware vSphere主机的SnapCenter 插件
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: 创建一个策略以备份数据存储库
      url: "/task-create-policies-vms.html"
    - title: 将数据存储库备份到Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: 将数据存储库备份到Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: 将数据存储库备份到Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: 将数据存储库备份到StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 管理数据存储库和虚拟机数据的保护
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 还原虚拟机数据
      url: "/task-restore-vm-data.html"
  - title: 备份和还原 Kubernetes 数据
    entries:
    - title: 保护您的 Kubernetes 数据
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: 备份到 Amazon S3
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: 备份到 Azure Blob
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: 备份到 Google Cloud
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: 管理 Kubernetes 备份
      url: "/task-manage-backups-kubernetes.html"
    - title: 从 Kubernetes 备份还原
      url: "/task-restore-backups-kubernetes.html"
  - title: 使用 REST API 实现自动化
    url: "/api-backup-restore.html"
  - title: 参考
    entries:
    - title: 备份策略设置
      url: "/concept-cloud-backup-policies.html"
    - title: 支持的 AWS 归档存储层
      url: "/reference-aws-backup-tiers.html"
    - title: 支持的 Azure 归档访问层
      url: "/reference-azure-backup-tiers.html"
    - title: 支持的Google归档存储层
      url: "/reference-google-backup-tiers.html"
    - title: 在 Azure 中配置用于多帐户访问的备份
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: 在非公开站点中还原BlueXP备份和恢复数据库
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: 重新启动BlueXP备份和恢复
      url: "/reference-restart-backup.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解有关BlueXP备份和恢复的信息
      url: concept-backup-to-cloud.html
    - title: 新增功能
      url: whats-new.html
    - title: 设置许可
      url: task-licensing-cloud-backup.html
    - title: 监控备份和还原作业的状态
      url: task-monitor-backup-jobs.html
    - title: 创建有关数据保护覆盖范围的报告
      url: task-report-inventory.html
  - title: 将 ONTAP 数据备份到云
    links:
    - title: 将 Cloud Volumes ONTAP 备份到 Amazon S3
      url: task-backup-to-s3.html
      flavor: aws
    - title: 将 Cloud Volumes ONTAP 备份到 Azure Blob
      url: task-backup-to-azure.html
      flavor: azure
    - title: 将 Cloud Volumes ONTAP 备份到 Google Cloud
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: 将内部 ONTAP 备份到 Amazon S3
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: 将内部 ONTAP 备份到 Azure Blob
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: 将内部 ONTAP 备份到 Google Cloud
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: 将内部ONTAP备份到ONTAP S3
      url: task-backup-onprem-to-ontap-s3.html
    - title: 将内部 ONTAP 备份到 StorageGRID
      url: task-backup-onprem-private-cloud.html
  - title: 管理 ONTAP 备份文件
    links:
    - title: 在其他卷上启用卷备份
      url: task-manage-backups-ontap.html#activate-backup-on-additional-volumes-in-a-working-environment
    - title: 编辑现有的云备份策略
      url: task-manage-backups-ontap.html#edit-an-existing-backup-to-cloud-policy
    - title: 向云策略添加新备份
      url: task-manage-backups-ontap.html#add-a-new-backup-to-cloud-policy
    - title: 更改分配给现有卷的策略
      url: task-manage-backups-ontap.html#change-the-backup-settings-assigned-to-existing-volumes
    - title: 创建手动卷备份
      url: task-manage-backups-ontap.html#create-a-manual-volume-backup-at-any-time
    - title: 查看每个卷的备份列表
      url: task-manage-backups-ontap.html#view-the-list-of-backups-for-each-volume
    - title: 管理复制关系
      url: task-manage-backups-ontap.html#manage-the-replication-relationship-with-the-source-volume
    - title: 删除备份
      url: task-manage-backups-ontap.html#delete-backups
  - title: 将应用程序数据备份到云
    links:
    - title: 将内部应用程序数据备份到Amazon Web Services
      flavor: aws
      url: task-backup-app-data-to-aws.html
    - title: 将内部应用程序数据备份到Microsoft Azure
      flavor: azure
      url: task-backup-app-data-to-azure.html
    - title: 将内部应用程序数据备份到Google Cloud
      flavor: gcp
      url: task-backup-app-data-to-gcp.html
    - title: 将内部应用程序数据备份到StorageGRID
      url: task-backup-app-data-to-storagegrid.html
    - title: 备份云原生Oracle数据库
      url: task-backup-cloud-native-oracle-data.html
    - title: 备份云原生SAP HANA数据库
      flavor: azure
      url: task-backup-cloud-native-sap-hana-data.html
    - title: 备份云原生SQL Server数据库
      url: task-backup-cloud-native-sql-data.html
  - title: 将数据存储库备份到云
    links:
    - title: 将数据存储库备份到Amazon Web Services
      flavor: aws
      url: task-backup-vm-data-to-aws.html
    - title: 将数据存储库备份到Microsoft Azure
      flavor: azure
      url: task-backup-vm-data-to-azure.html
    - title: 将数据存储库备份到Google Cloud Platform
      flavor: gcp
      url: task-backup-vm-data-to-gcp.html
    - title: 将数据存储库备份到StorageGRID
      url: task-backup-vm-data-to-storagegrid.html
  - title: 从云中还原数据
    links:
    - title: 还原ONTAP 卷数据
      url: task-restore-backups-ontap.html
    - title: 还原内部Oracle应用程序数据
      url: task-restore-oracle-data.html
    - title: 还原内部SQL Server应用程序数据
      url: task-restore-sql-data.html
    - title: 还原云原生Oracle应用程序数据
      url: task-restore-cloud-native-oracle-data.html
    - title: 还原云原生SAP HANA应用程序数据
      flavor: azure
      url: task-restore-cloud-native-sap-hana-data.html
    - title: 还原云原生SQL Server数据
      url: task-restore-cloud-native-sql-data.html
    - title: 还原虚拟机数据
      url: task-restore-vm-data.html
    - title: 还原Kubernetes卷数据
      url: task-restore-backups-kubernetes.html
  - title: 将 Kubernetes 数据备份到云
    links:
    - title: 将Kubbernetes集群备份到Amazon S3
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: 将Kubnetes集群备份到Azure Blb
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: 将Kubbernetes集群备份到Google Cloud
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: BlueXP备份和恢复博客
      url: https://bluexp.netapp.com/blog/topic/cloud-backup
    - title: BlueXP备份和恢复用例
      url: https://bluexp.netapp.com/cloud-backup
    - title: BlueXP备份和恢复视频
      url: https://youtube.com/playlist?list=PLdXI3bZJEw7modoLQEVUHoQ8DJyVk_1wU
    - title: BlueXP网络研讨会
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
