---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: '在无法访问Internet的站点中使用BlueXP备份和恢复时(称为"专用模式")、BlueXP备份和恢复配置数据将备份到存储备份的StorageGRID或ONTAP S3存储分段。如果将来您的问题描述与BlueXP Connector主机系统结合使用、则可以部署新的Connector并还原关键的BlueXP备份和恢复数据。' 
---
= 在非公开站点中还原BlueXP备份和恢复数据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在无法访问Internet的站点中使用BlueXP备份和恢复时、称为_private mode_、BlueXP备份和恢复配置数据将备份到存储备份的StorageGRID或ONTAP S3存储分段。如果将来您的问题描述与BlueXP Connector主机系统结合使用、则可以部署新的Connector并还原关键的BlueXP备份和恢复数据。

请注意、如果在云提供商处部署了BlueXP Connector的SaaS环境中使用BlueXP备份和恢复、或者在可访问Internet的您自己的主机系统上使用BlueXP备份和恢复、则所有重要的BlueXP备份和恢复配置数据都会在云中进行备份和保护。如果您的问题描述具有连接器、只需创建一个新连接器并添加您的工作环境、备份详细信息就会自动还原。

备份的数据有两种：

* BlueXP备份和恢复数据库-包含所有卷、备份文件、备份策略和配置信息的列表。
* 索引目录文件-包含用于"搜索和还原"功能的详细索引、使您在查找要还原的卷数据时可以快速高效地进行搜索。


此数据每天午夜备份一次、每个文件最多保留7个副本。如果Connector管理多个内部ONTAP工作环境、BlueXP备份和恢复文件将位于首先激活的工作环境的存储分段中。


TIP: BlueXP备份和恢复数据库或索引目录文件中从未包含任何卷数据。



== 将BlueXP备份和恢复数据还原到新的Connector

如果您的内部连接器发生灾难性故障、则需要安装新的Connector、然后将BlueXP备份和恢复数据还原到新的Connector。

要将您的BlueXP备份和恢复系统恢复为工作状态、您需要执行4项任务：

* 安装新的BlueXP Connector
* 还原BlueXP备份和恢复数据库
* 还原索引目录文件
* 在BlueXP UI中重新发现所有内部ONTAP 系统和StorageGRID 系统


确认系统恢复正常运行后、建议您创建新的备份文件。

.您需要的内容
您需要从存储备份文件的StorageGRID或ONTAP S3存储分段访问最新的数据库和索引备份：

* BlueXP备份和恢复MySQL数据库文件
+
此文件位于存储分段中的以下位置 `netapp-backup-<GUID>/mysql_backup/`，并命名为 `CBS_DB_Backup_<day>_<month>_<year>.sql`。

* 索引目录备份zip文件
+
此文件位于存储分段中的以下位置 `netapp-backup-<GUID>/catalog_backup/`，并命名为 `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`。





=== 在新的内部Linux主机上安装新的Connector

安装新的BlueXP Connector时、请确保下载的软件版本与原始Connector上安装的软件版本相同。定期更改BlueXP备份和恢复数据库结构可能会使较新的软件版本与原始数据库备份不兼容。您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["还原备份数据库后、将Connector软件升级到最新版本"^]。

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["在新的内部Linux主机上安装BlueXP Connector"^]
. 使用刚刚创建的管理员用户凭据登录到BlueXP。




=== 还原BlueXP备份和恢复数据库

. 将MySQL备份从备份位置复制到新的Connector主机。我们将使用下面的示例文件名"CBS_DB_Backup_23_05_2023.SQL"。
. 根据您使用的是Docker容器还是Podman容器、使用以下命令之一将备份复制到MySQL Docker容器：
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. 根据您使用的是Docker容器还是Podman容器、使用以下命令之一输入MySQL容器Shell：
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. 在容器Shell中、部署"env"。
. 您需要MySQL数据库密码、因此请复制密钥"mysql_root_password"的值。
. 使用以下命令还原BlueXP备份和恢复MySQL数据库：
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. 使用以下SQL命令验证是否已正确还原BlueXP备份和恢复MySQL数据库：
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
输入密码。

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
检查显示的卷是否与原始环境中的卷相同。





=== 还原索引目录文件

. 将索引目录备份zip文件(我们将使用示例文件名"索引_目录_DB_Backup_catalogdb1_23_05_2023.zip")从备份位置复制到"/opp/application/NetApp/CBs"文件夹中的新Connector主机。
. 使用以下命令解压缩"索引_目录_DB_Backup_catalogdb1_23_05_2023.zip"文件：
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. 运行*ls*命令，确保已创建文件夹"catalogdb1"，并在其下面创建了子文件夹"changes"和"fSnaps"。




=== 发现ONTAP 集群和StorageGRID 系统

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["了解所有内部ONTAP 工作环境"^] 您先前环境中提供的。这包括您用作S3服务器的ONTAP系统。
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["发现您的StorageGRID 系统"^]。




=== 设置StorageGRID 环境详细信息

添加与您的ONTAP 工作环境关联的StorageGRID 系统的详细信息、这些详细信息是在使用的原始连接器设置中设置的 https://docs.netapp.com/us-en/bluexp-automation/index.html["BlueXP API"^]。

您需要对要将数据备份到StorageGRID 的每个ONTAP 系统执行这些步骤。

. 使用以下OAuth/令牌API提取授权令牌。
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
此API将返回如下响应。您可以检索授权令牌、如下所示。

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. 使用租户/外部/资源API提取工作环境ID和X-Agent-ID。
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
此API将返回如下响应。"resourcesIdentifier"下的值表示_WorkingEnvironment ID_、"agentId"下的值表示_x-agent-id_。

. 使用与工作环境关联的StorageGRID 系统的详细信息更新BlueXP备份和恢复数据库。请务必输入StorageGRID 的完全限定域名以及访问密钥和存储密钥、如下所示：
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== 验证BlueXP备份和恢复设置

. 选择每个ONTAP 工作环境、然后单击右侧面板中备份和恢复服务旁边的*查看备份*。
+
您应该能够查看为卷创建的所有备份。

. 在还原信息板的搜索和还原部分下、单击*索引设置*。
+
确保先前已启用索引编目的工作环境保持启用状态。

. 从搜索和还原页面中、运行几次目录搜索以确认索引目录还原已成功完成。

