---
sidebar: sidebar 
permalink: reference-prereq-protect-cloud-native-app-data.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in 
summary: 创建备份之前、请先完成前提条件。 
---
= 前提条件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应有权访问Cloud Manager、创建Cloud Manager帐户、创建工作环境和Connector、并部署适用于Oracle的SnapCenter 插件。



== 访问 Cloud Manager

您应该 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-signing-up.html["注册到 NetApp Cloud Central"]， link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["登录到 Cloud Manager"]，然后设置 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["NetApp 帐户"]。



== 为ONTAP 工作环境创建FSX

您应创建托管数据库的Amazon FSX for ONTAP 工作环境。有关信息、请参见 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["开始使用适用于 ONTAP 的 Amazon FSX"] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["创建和管理适用于 ONTAP 的 Amazon FSX 工作环境"]。

您可以使用Cloud Manager或AWS创建NetApp FSX。如果您已使用AWS创建、则应在Cloud Manager中发现适用于ONTAP 系统的FSX。



== 创建连接器

客户管理员需要在AWS中部署一个连接器、以使Cloud Manager能够管理公有 云环境中的资源和流程。

有关信息、请参见 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["通过 Cloud Manager 在 AWS 中创建连接器"]。

* 您应使用相同的连接器来管理FSX工作环境和Oracle数据库。
* 如果您的FSX工作环境和Oracle数据库位于同一个VPC中、则可以在同一个VPC中部署此连接器。
* 如果您的FSX工作环境和Oracle数据库位于不同的vPC中：
+
** 如果在FSX上配置了NAS (NFS)工作负载、则可以在任一VPC上创建连接器。
** 如果您仅配置了SAN工作负载、并且不打算使用任何NAS (NFS)工作负载、则应在创建FSX系统的VPC中创建连接器。
+

NOTE: 要使用NAS (NFS)工作负载、您应在Oracle数据库VPC和FSX VPC之间设置传输网关。作为浮动IP地址的NFS IP地址只能通过传输网关从另一个VPC访问。我们无法通过对等VPC来访问浮动IP地址。





创建连接器后、单击*画布*>*添加工作环境*、然后按照提示添加工作环境。确保已从连接器连接到Oracle数据库主机和FSX工作环境。此连接器应能够连接到FSX工作环境的集群管理IP地址。


IMPORTANT: 创建连接器后、单击*连接器>管理连接器*；选择连接器名称并复制连接器ID。



== 部署适用于Oracle的SnapCenter 插件

您应在每个Oracle数据库主机上部署适用于Oracle的SnapCenter 插件。根据Oracle主机是否启用了基于SSH密钥的身份验证、您可以按照以下方法之一部署此插件。


NOTE: 确保在每个Oracle数据库主机上安装了Java 8、并且正确设置了java_home变量。



=== 使用基于SSH密钥的身份验证进行插件部署

如果在Oracle主机上启用了基于SSH密钥的身份验证、则可以执行以下步骤来部署此插件。在执行这些步骤之前、请确保已启用与连接器的SSH连接。

. 以非root用户身份登录到Connector VM。
. 获取基本挂载路径。`sUdo Docker volume ls | grep SCS_cloud _volume _查｛'print $2'｝_ xargs sudo Docker volume inspect _ grep mountpoint`
. 部署此插件。
+
`sUdo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh -host <host_name>-sshkey <ssh_key_file>-username <user_name>-port <ssh_port>-pluginport <plug_port>-installdir <install_dir>`

+
** host_name是Oracle主机的名称、这是一个必需参数。
** SSH_key_file是用于连接到Oracle主机的SSH密钥、这是一个必需参数。
** user_name：在Oracle主机上具有SSH权限的用户、这是一个可选参数。默认值为EC2-user。
** SSH_port：Oracle主机上的SSH端口、这是一个可选参数。默认值为22
** plugin_port：插件使用的端口、这是一个可选参数。默认值为8145
** install_dir：要部署此插件的目录、这是一个可选参数。默认值为/opt。




例如：`sUdo /var/lib/docker/volumes/service-manager-2_cloudmanager_SCS_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh -host xxx.xx.x.x -sshkey /keys/netapp-ssh.ppfk`



=== 手动部署此插件

如果Oracle主机上未启用基于SSH密钥的身份验证、则应执行以下手动步骤来部署此插件。

. 登录到Connector VM。
. 下载SnapCenter Linux主机插件二进制文件。`sUdo Docker exec -it cloudmanager_SCS_cloud curl -X get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. 获取基本挂载路径。`sUdo Docker volume ls | grep SCS_cloud _volume _查｛'print $2'｝_ xargs sudo Docker volume inspect _ grep mountpoint`
. 获取下载插件的二进制路径。`s使用ls <base_mount_path>$(sudo Docker ps|grep -po"cloudmanager_SCS_cloud：.*？"|sed -e 's/*$//'|cut -f2 -d"：")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. 使用scp或其他替代方法将_snapcenter_linux_host_plugin_SCS.bin_复制到每个Oracle数据库主机。
. 在Oracle数据库主机上、运行以下命令为二进制文件启用执行权限。`chmod +x snapcenter_linux_host_plugin_SCS.bin`
. 以root用户身份部署Oracle插件。`。/snapcenter_linux_host_plugin_scs.bin -I silent`
. 将_certificate.p12_从Connector VM的_<base_mount_path>/client/certificate/_路径复制到插件主机上的_/var/opt/snapcenter/spl/etc/。
+
.. 导航到_/var/opt/snapcenter/spl/etc_并执行keytool命令以导入证书。`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass SnapCenter -deststorepass SnapCenter -srccalibras agentcert -destalias agentcert -noprop`
.. 重新启动SPL：`systemctl restart spl`



