---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: 如果在无法访问Internet的站点上使用BlueXP备份和恢复、则如果您的问题描述 使用的是BlueXP连接器主机系统、则需要定期备份关键的BlueXP备份和恢复文件。这样、您就可以部署新的Connector并还原关键的BlueXP备份和恢复数据。 
---
= 在非公开站点中备份和还原BlueXP备份和恢复数据
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果在无法访问Internet的站点上使用BlueXP备份和恢复、则如果您的问题描述 使用的是BlueXP连接器主机系统、则需要定期备份关键的BlueXP备份和恢复文件。这样、您就可以部署新的Connector并还原关键的BlueXP备份和恢复数据。

如果您在部署了BlueXP Connector的SaaS环境中或您自己具有Internet访问权限的主机系统中使用BlueXP备份和恢复、则所有重要的BlueXP备份和恢复配置数据都会备份并存储在云中。如果在无法访问Internet的站点(称为"受限模式"或"非公开站点")中使用BlueXP备份和恢复、则此BlueXP备份和恢复信息仅存储在本地连接器系统上。

我们将介绍如何将关键的BlueXP备份和恢复数据备份到已连接的StorageGRID 系统、以及如何在必要时将数据恢复到新连接器上。



== 备份关键的BlueXP备份和恢复数据

您需要备份两种类型的数据：

* BlueXP备份和恢复数据库
* 索引目录文件(用于搜索和还原功能)



NOTE: 您应计划定期备份此BlueXP备份和恢复数据、以便始终能够访问最新数据。

请注意、BlueXP备份和恢复数据库或索引目录文件中从未包含任何卷数据。



=== 备份BlueXP备份和恢复数据库

BlueXP备份和恢复数据库包含所有卷、备份文件、备份策略和配置信息的列表。

.步骤
. 使用适当的凭据登录到Connector主机系统。
. 输入以下命令、输入MySQL容器Shell：
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. 在容器Shell中、部署"env"。
. 您需要MySQL数据库密码、因此请复制密钥"mysql_root_password"的值。
. 输入以下命令、备份BlueXP备份和恢复MySQL数据库：
+
[source, cli]
----
mysqldump --user root --password -p cloud_backup --result-file=mysql.dump.cloud_backup.sql
----
. 输入以下命令、从MySQL Docker容器复制MySQL数据库备份：
+
[source, cli]
----
docker cp ds_mysql_1:/mysql.dump.cloud_backup.sql .
----
. 将备份复制到网络中的安全位置。如果要创建到本地StorageGRID 卷的ONTAP 备份、则可以使用该位置的系统。




=== 备份索引目录文件

索引目录用于搜索和还原功能。它包含有关每个卷和每个备份文件的信息、可使您在查找要还原的卷数据时快速高效地进行搜索。

. 在Connector主机系统上、将目录更改为"/opt应用程序/NetApp/CBS "。
. 找到索引目录文件夹。它以字符串*目录*开头。
. 输入以下命令以压缩"catalog <_xxxxxx_>"文件夹：
+
[source, cli]
----
zip -r catalogxxxxxx.zip catalogxxxxxx
----
. 将压缩后的备份复制到网络中的安全位置。




== 将BlueXP备份和恢复数据还原到新的Connector

如果您的内部连接器发生灾难性故障、则需要安装新的Connector、然后将BlueXP备份和恢复数据还原到新的Connector。

要将您的BlueXP备份和恢复系统恢复为工作状态、您需要执行4项任务：

* 安装新的BlueXP Connector
* 还原BlueXP备份和恢复数据库
* 还原索引目录文件
* 在BlueXP UI中重新发现所有内部ONTAP 系统和StorageGRID 系统


确认系统恢复正常运行后、建议您创建新的备份文件。



=== 在新的内部Linux主机上安装新的Connector

安装新的BlueXP Connector时、请确保下载的软件版本与原始Connector上安装的软件版本相同。定期更改BlueXP备份和恢复数据库结构可能会使较新的软件版本与原始数据库备份不兼容。您可以 https://["还原备份数据库后、将Connector软件升级到最新版本"^]。

. https://["在新的内部Linux主机上安装BlueXP Connector"^]
. 使用刚刚创建的管理员用户凭据登录到BlueXP。




=== 还原BlueXP备份和恢复数据库

. 将MySQL备份从安全位置复制到新的Connector主机。
. 使用以下命令将备份复制到MySQL Docker容器：
+
[source, cli]
----
docker cp mysql.dump.cloud_backup.sql ds_mysql_1:/.
----
. 使用以下命令输入MySQL容器Shell：
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. 在容器Shell中、部署"env"。
. 您需要MySQL数据库密码、因此请复制密钥"mysql_root_password"的值。
. 使用以下命令还原BlueXP备份和恢复MySQL数据库：
+
[source, cli]
----
mysql -u root -p cloud_backup < mysql.dump.cloud_backup.sql
----
. 使用以下SQL命令验证是否已正确还原BlueXP备份和恢复MySQL数据库：
+
[source, cli]
----
# mysql -u root -p cloud_backup
----
+
输入密码。

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
检查显示的卷是否与原始环境中的卷相同。





=== 还原索引目录文件

. 将索引目录备份zip文件从安全位置复制到"/op/application/NetApp/CBS "文件夹中的新连接器主机。
. 使用以下命令解压缩"catalogxxxxxx.zip文件：
+
[source, cli]
----
unzip catalogxxxxxx.zip
----
. 运行* ls*命令以确保已创建"catalogxxxxxx"文件夹、并且子文件夹"changes"和"snapshots"位于下方。




=== 发现ONTAP 集群和StorageGRID 系统

. https://["了解所有内部ONTAP 工作环境"^] 您先前环境中提供的。
. https://["发现您的StorageGRID 系统"^]。




=== 设置StorageGRID 环境详细信息

添加与您的ONTAP 工作环境关联的StorageGRID 系统的详细信息、这些详细信息是在使用的原始连接器设置中设置的 https://["BlueXP API"^]。

您需要对要将数据备份到StorageGRID 的每个ONTAP 系统执行这些步骤。

. 使用以下OAuth/令牌API提取授权令牌。
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
此API将返回如下响应。您可以检索授权令牌、如下所示。

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. 使用租户/外部/资源API提取工作环境ID和X-Agent-ID。
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
此API将返回如下响应。"resourcesIdentifier"下的值表示_WorkingEnvironment ID_、"agentId"下的值表示_x-agent-id_。

. 使用与工作环境关联的StorageGRID 系统的详细信息更新BlueXP备份和恢复数据库。请务必输入StorageGRID 的完全限定域名以及访问密钥和存储密钥、如下所示：
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== 验证BlueXP备份和恢复设置

. 选择每个ONTAP 工作环境、然后单击右侧面板中备份和恢复服务旁边的*查看备份*。
+
您应该能够查看为卷创建的所有备份。

. 在还原信息板的搜索和还原部分下、单击*索引设置*。
+
确保先前已启用索引编目的工作环境保持启用状态。

. 从搜索和还原页面中、运行几次目录搜索以确认索引目录还原已成功完成。

