---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, backup, restore, backup and recovery 
summary: 已知限制用于说明此产品版本不支持的功能或无法与其正确交互的功能。仔细审查这些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制用于说明此产品版本不支持的功能或无法与其正确交互的功能。仔细审查这些限制。



== ONTAP卷的备份和还原限制

* BlueXP  备份和恢复将Cloud Volume ONTAP备份到AWS中国地区(包括北京和宁夏)的对象存储；但是、您可能需要先手动修改身份和访问管理(IAM)策略。
+
有关在AWS中创建连接器的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["在AWS中安装连接器"^]。

+
有关博文中的其他详细信息，请参见https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["BlueXP  备份和恢复功能博客2023年5月"^]。

* BlueXP  备份和恢复不支持Microsoft Azure中国地区。
+
有关在Azure中创建连接器的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-bluexp.html["在Azure中安装Connector"^]。





=== 复制限制

* 一次只能选择一个FlexGroup卷进行复制。您需要分别为每个FlexGroup卷激活备份。
+
FlexVol卷没有限制—您可以选择工作环境中的所有FlexVol卷并分配相同的备份策略。

* 中支持以下功能 https://docs.netapp.com/us-en/bluexp-replication/index.html["BlueXP复制服务"]，但在使用BlueXP备份和恢复的复制功能时不能：
+
** 不支持从卷A复制到卷B以及从卷B复制到卷C的级联配置支持从卷A复制到卷B
** 不支持在FSx for ONTAP系统之间复制数据。
** 不支持创建卷的一次性复制。


* 从内部ONTAP系统创建复制时、如果目标Cloud Volumes ONTAP系统上的ONTAP版本为9.8、9.9或9.11、则仅允许使用镜像存储策略。




=== 备份到对象限制

* 在没有为备份策略分配任何卷的情况下创建或编辑此策略时、保留的备份数最多可为1018个。为策略分配卷后、您可以编辑此策略以创建多达4000个备份。
* 备份数据保护(DP)卷时：
+
** 与SnapMirror标签`APP_consistent`和`all_source_snapshot`的关系不会备份到云。
** 如果在SnapMirror目标卷上创建Snapshot的本地副本(无论使用的SnapMirror标签如何)、则这些Snapshot不会作为备份移动到云中。此时、您需要为源DP卷创建一个包含所需标签的Snapshot策略、以便BlueXP备份和恢复功能对其进行备份。


* 无法将FlexGroup 卷备份移至归档存储。
* 如果集群运行的是ONTAP 9.13.1或更高版本、则FlexGroup卷备份可以使用DataLock和防软件保护。
* 支持 SVM-DR 卷备份，但有以下限制：
+
** 仅支持从 ONTAP 二级系统进行备份。
** 应用于卷的Snapshot策略必须是BlueXP备份和恢复所识别的策略之一、包括每日、每周、每月等 无法识别默认的"sm_created"策略(用于*镜像所有快照*)、并且DP卷不会显示在可备份的卷列表中。
** 从源或目标进行备份时、SVM-DR和卷备份和恢复完全独立工作。唯一的限制是、SVM-DR不会复制SnapMirror云关系。在灾难恢复情形下、如果SVM在二级位置联机、则必须手动更新SnapMirror云关系。




* MetroCluster 支持：
+
** 使用ONTAP 9.12.1 GA或更高版本时、如果连接到主系统、则支持备份。整个备份配置将传输到二级系统、以便在切换后自动继续备份到云。您无需在二级系统上设置备份(实际上、您会受到限制)。
** 使用ONTAP 9.12.0及更早版本时、仅支持从ONTAP二级系统进行备份。
** 目前不支持FlexGroup 卷的备份。


* 数据保护卷不支持使用*立即备份*按钮进行临时卷备份。
* 不支持 SM-BC 配置。
* ONTAP 不支持扇出从一个卷到多个对象存储的SnapMirror关系；因此、BlueXP备份和恢复不支持此配置。
* 目前、Amazon S3、Azure和StorageGRID 支持对象存储上的WORM/Compliance模式。这称为DataLock功能、必须使用BlueXP备份和恢复设置进行管理、而不是使用云提供商界面进行管理。




=== 还原限制

这些限制适用于恢复文件和文件夹的搜索和还原以及浏览和还原方法；除非特别说明。

* 浏览和还原一次最多可还原100个单个文件。
* 搜索和还原一次可以还原1个文件。
* 使用ONTAP 9.13.0或更高版本时、浏览和还原以及搜索和还原可以还原文件夹及其所有文件和子文件夹。
+
如果使用的ONTAP 版本高于9.11.1、但低于9.13.0、则还原操作只能还原选定文件夹、并且该文件夹中的文件不会还原子文件夹或子文件夹中的文件。

+
如果使用的ONTAP 版本早于9.11.1、则不支持文件夹还原。

* 只有当集群运行的是ONTAP 9.13.1及更高版本时、归档存储中的数据才支持目录/文件夹还原。
* 只有当集群运行的是ONTAP 9.13.1及更高版本时、使用DataLock保护的数据才支持目录/文件夹还原。
* 当前不支持从复制和/或本地快照还原目录/文件夹。
* 不支持从FlexGroup 卷还原到FlexVol 卷、或将FlexVol 卷还原到FlexGroup 卷。
* 要还原的文件必须使用与目标卷上的语言相同的语言。如果语言不同，您将收到一条错误消息。
* 将数据从Azure归档存储还原到StorageGRID 系统时、不支持_High_还原优先级。
* 如果您备份了DP卷、然后决定中断与该卷的SnapMirror关系、则无法将文件还原到该卷、除非同时删除SnapMirror关系或反转SnapMirror方向。
* 快速还原限制：
+
** 目标位置必须是使用ONTAP 9.13.0或更高版本的Cloud Volumes ONTAP系统。
** 归档存储中的备份不支持此功能。
** 只有在创建云备份的源系统运行的是ONTAP 9.12.1或更高版本时、才支持FlexGroup卷。
** 只有在创建云备份的源系统运行的是ONTAP 9.11.0或更高版本时、才支持SnapLock卷。



