---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: 在BlueXP中注册适用于VMware vSphere主机的SnapCenter 插件。 
---
= 注册适用于VMware vSphere主机的SnapCenter 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应在BlueXP中注册适用于VMware vSphere的SnapCenter 插件主机、以显示要显示的数据存储库和虚拟机。只有具有管理访问权限的用户才能注册适用于VMware vSphere的SnapCenter 插件主机。


NOTE: 您可以在BlueXP中注册多个适用于VMware vSphere的SnapCenter 插件主机。但是、注册后、您将无法删除适用于VMware vSphere的SnapCenter 插件主机。

.步骤
. 在BlueXP UI中、单击*保护*>*备份和恢复*>*虚拟机*。
. 从*设置*下拉列表中、单击*适用于VMware vSphere的SnapCenter 插件*。
. 单击*注册适用于VMware vSphere的SnapCenter 插件*。
. 指定以下详细信息：
+
.. 在适用于VMware vSphere的SnapCenter 插件字段中、指定适用于VMware vSphere的SnapCenter 插件主机的FQDN或IP地址。
.. 在端口字段中、指定运行适用于VMware vSphere的SnapCenter 插件主机的端口号。
+
您应确保此端口已打开、以便适用于VMware vSphere的SnapCenter 插件主机和BlueXP之间能够进行通信。

.. 在用户名和密码字段中、指定具有管理员角色的用户的凭据。


. 单击 * 注册 * 。


* 完成后 *

单击*备份和恢复*>*虚拟机*可查看使用适用于VMware vSphere的已注册SnapCenter 插件主机保护的所有数据存储库和虚拟机。
