---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection, sql server, workloads, volumes, snapshots' 
summary: 了解BlueXP备份和恢复的新增功能。 
---
= BlueXP 备份和恢复的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP备份和恢复的新增功能。



== 2025年7月28日

此BlueXP  备份和恢复版本包含以下更新。



=== Kubernetes 工作负载支持作为公共技术预览

此版本的BlueXP backup and recovery引入了对发现和管理 Kubernetes 工作负载的支持：

* 发现由NetApp ONTAP支持的 Red Hat OpenShift 和开源 Kubernetes 集群，无需共享 kubeconfig 文件。
* 使用统一的控制平面发现、管理和保护跨多个 Kubernetes 集群的应用程序。
* 将 Kubernetes 应用程序的备份和恢复数据移动操作卸载到NetApp ONTAP。
* 协调本地和基于对象存储的应用程序备份。
* 将整个应用程序和单个资源备份并恢复到任何 Kubernetes 集群。
* 使用在 Kubernetes 上运行的容器和虚拟机。
* 使用执行挂钩和模板创建应用程序一致的备份。




== 2025年7月14日

此BlueXP  备份和恢复版本包含以下更新。



=== 增强型ONTAP卷仪表板

2025 年 4 月，我们推出了增强型ONTAP卷仪表板的预览版，它速度更快、更高效。

此仪表板旨在帮助企业客户处理大量工作负载。即使对于拥有 20,000 个卷的客户，新仪表板也能在 10 秒内加载完成。

预览版成功上线，并获得了众多预览版用户的积极反馈，我们现已将其设为所有客户的默认体验。准备好迎接极速仪表板吧！

有关详细信息，请参见 link:br-use-dashboard.html["在仪表板中查看保护健康状况"]。



=== Microsoft SQL Server 工作负载支持作为公共技术预览

此版本的BlueXP backup and recovery提供了更新的用户界面，使您能够使用BlueXP backup and recovery服务中熟悉的 3-2-1 保护策略来管理 Microsoft SQL Server 工作负载。使用此新版本，您可以将这些工作负载备份到主存储，复制到辅助存储，然后备份到云对象存储。

您可以通过完成此步骤注册预览 https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["预览注册表"^] 。


NOTE: 本文档旨在介绍如何保护 Microsoft SQL Server 工作负载，目前仅提供技术预览版。NetAppNetApp在正式发布之前修改此预览版产品详细信息、内容和时间表的权利。

此版本的BlueXP backup and recovery包括以下更新：

* *3-2-1 备份功能*：此版本集成了SnapCenter功能，使您能够通过BlueXP backup and recovery用户界面使用 3-2-1 数据保护策略来管理和保护您的SnapCenter资源。
* *从SnapCenter导入*：您可以将SnapCenter备份数据和策略导入BlueXP backup and recovery。
* *重新设计的用户界面*为管理备份和恢复任务提供了更直观的体验。
* *备份目标*：您可以在 Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID和ONTAP S3 环境中添加存储桶，以用作 Microsoft SQL Server 工作负载的备份目标。
* *工作负载支持*：此版本支持您备份、还原、验证和克隆 Microsoft SQL Server 数据库和可用性组。（未来版本将添加对其他工作负载的支持。）
* *灵活的恢复选项*：此版本使您能够在发生损坏或意外数据丢失的情况下将数据库恢复到原始位置和备用位置。
* *即时生产副本*：在几分钟内（而不是几小时或几天）生成用于开发、测试或分析的节省空间的生产副本。
* 此版本包括创建详细报告的功能。


有关保护 Microsoft SQL Server 工作负载的详细信息，请参阅link:br-use-mssql-protect-overview.html["保护 Microsoft SQL Server 工作负载概述"] 。



== 2025 年 6 月 9 日

此BlueXP  备份和恢复版本包含以下更新。



=== 索引目录支持更新

2025 年 2 月，我们推出了更新的索引功能（索引目录 v2），您可以在“搜索和还原”数据还原方法中使用此功能。上一版本显著提升了本地环境中的数据索引性能。在此版本中，索引目录现已可在 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 环境中使用。

如果您是新客户，所有新环境均默认启用索引目录 v2。如果您是现有客户，您可以重新索引您的环境以利用索引目录 v2。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。执行搜索和恢复时，选择“*启用索引*”选项。

索引目录可以跟踪每个卷和备份文件，使您的搜索快速而高效。

有关详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["启用搜索和还原索引"]。



=== Azure 专用链接终结点和服务终结点

通常， BlueXP backup and recovery会与云提供商建立一个私有端点来处理保护任务。此版本引入了一项可选设置，可让您启用或禁用 BlueXP 备份和恢复自动创建私有端点的功能。如果您希望更好地控制私有端点的创建过程，这项设置可能会对您有所帮助。

您可以在启用保护或开始恢复过程时启用或禁用此选项。

如果禁用此设置，则必须手动创建专用端点，以确保 BlueXP 备份和恢复功能正常运行。如果没有正确的连接，您可能无法成功执行备份和恢复任务。



=== ONTAP S3 上支持 SnapMirror 到云重新同步

上一版本引入了对 SnapMirror 到云重新同步 (SM-C Resync) 的支持。该功能简化了 NetApp 环境中卷迁移期间的数据保护。此版本增加了对 ONTAP S3 以及其他兼容 S3 的提供商（例如 Wasabi 和 MinIO）上的 SM-C Resync 的支持。



=== 为 StorageGRID 带来您自己的存储桶

当您在对象存储中为工作环境创建备份文件时，BlueXP 备份和恢复功能会默认在您配置的对象存储帐户中为备份文件创建容器（存储桶或存储帐户）。之前，您可以覆盖此设置，并为 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。在此版本中，您现在可以自带 StorageGRID 对象存储容器。

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["创建您自己的对象存储容器"]



== 2025年5月13日

此BlueXP  备份和恢复版本包含以下更新。



=== SnapMirror到云重新同步以进行卷迁移

SnapMirror到云重新同步功能可简化NetApp环境中卷迁移期间的数据保护和连续性。使用SnapMirror逻辑复制(LRSE)将卷迁移到内部NetApp部署或Cloud Volumes ONTAP或Cloud Volumes Service等基于云的解决方案时、SnapMirror到云重新同步可确保现有云备份保持完好且正常运行。

此功能无需执行耗时且资源密集型的重新基线操作、从而可以在迁移后继续执行备份操作。此功能在工作负载迁移方案中非常有用、可同时支持FlexVol和FlexGroup、并可从ONTAP 9.161版开始使用。

通过在不同环境之间保持备份连续性、SnapMirror到云重新同步可提高运营效率、并降低混合云和多云数据管理的复杂性。

有关如何执行重新同步操作的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-migrate-resync.html["使用SnapMirror迁移卷到云重新同步"]。



=== 支持第三方MinIO对象存储(预览)

BlueXP  备份和恢复现在将其支持扩展到第三方对象存储、并主要侧重于MinIO。通过这一新的预览功能、您可以利用任何与S3兼容的对象存储来满足备份和恢复需求。

在此预览版本中、我们希望确保在推出完整功能之前与第三方对象存储实现强大集成。我们鼓励您探索这项新功能、并提供反馈以帮助改进服务。


IMPORTANT: 此功能不应在生产环境中使用。

*预览模式限制*

在预览此功能时、存在一些限制：

* 不支持自带存储分段(BYOB)。
* 不支持在策略中启用DataLock。
* 不支持在策略中启用归位模式。
* 仅支持内部ONTAP环境。
* 不支持MetroCluster。
* 不支持用于启用存储分段级别加密的选项。


* 入门 *

要开始使用此预览功能、您必须在BlueXP  连接器上启用一个标志。然后、您可以通过在备份部分中选择*第三方兼容*对象存储、在保护工作流中输入您的Minio第三方对象存储的连接详细信息。



== 2025年4月16日

此BlueXP  备份和恢复版本包含以下更新。



=== UI改进

此版本通过简化界面增强了用户体验：

* 在V2信息板的卷表中、从卷表中删除聚合列以及Snapshot策略、备份策略和复制策略列后、布局将更加简化。
* 从下拉列表中排除未激活的工作环境可减少界面的干扰、提高导航效率并加快加载速度。
* 禁用标记列排序后、您仍可查看标记、以确保重要信息始终易于访问。
* 去除保护图标上的标签有助于使外观更清晰、并减少加载时间。
* 在工作环境激活过程中、对话框会显示一个加载图标、以提供反馈、直到发现过程完成、从而提高系统操作的透明度和可信度。




=== 增强的卷信息板(预览)

现在、卷信息板加载时间不到10秒、从而提供了一个速度更快、效率更高的界面。此预览版可供部分客户使用、让他们可以及早了解这些改进。



=== 支持第三方芥末对象存储(预览)

BlueXP  备份和恢复现在将其支持扩展到第三方对象存储、主要侧重于芥末。通过这一新的预览功能、您可以利用任何与S3兼容的对象存储来满足备份和恢复需求。



==== 开始使用芥末

要开始使用第三方存储作为对象存储、必须在BlueXP  连接器中启用一个标志。然后、您可以输入第三方对象存储的连接详细信息、并将其集成到备份和恢复工作流中。

.步骤
. 通过SSH连接到您的连接器。
. 转到BlueXP  备份和恢复CBS服务器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 通过VIM或任何其他编辑器打开 `default.json`文件夹中的文件 `config`：
+
[listing]
----
vi default.json
----
. 修改 `allow-s3-compatible`：false到 `allow-s3-compatible`：true。
. 保存更改。
. 退出容器。
. 重新启动BlueXP  备份和恢复CBS服务器容器。


.结果
重新打开容器后、打开BlueXP  备份和恢复UI。启动备份或编辑备份策略时、您将看到新的提供程序"S3兼容"与AWS、Microsoft Azure、Google Cloud、StorageGRID和ONTAP S3的其他备份提供程序一起列出。



==== 预览模式限制

在预览此功能时、请考虑以下限制：

* 不支持自带存储分段(BYOB)。
* 不支持在策略中启用DataLock。
* 不支持在策略中启用归份模式。
* 仅支持内部ONTAP环境。
* 不支持MetroCluster。
* 不支持用于启用存储分段级别加密的选项。


在此预览期间、我们建议您探索这一新功能、并在推出完整功能之前提供有关与第三方对象存储集成的反馈。



== 2025年3月17日

此BlueXP  备份和恢复版本包含以下更新。



=== SMB快照浏览

此BlueXP  备份和恢复更新解决了客户无法在SMB环境中浏览本地快照的问题。



=== AWS GovCloud环境更新

此BlueXP  备份和恢复更新修复了由于TLS证书错误而导致UI无法连接到AWS GovCloud环境的问题。已使用BlueXP  连接器主机名而非IP地址解决此问题。



=== 备份策略保留限制

以前、BlueXP  备份和恢复用户界面会将备份限制为999个副本、而命令行界面则允许更多副本。现在、您最多可以将4、000个卷连接到一个备份策略、并将1、018个未连接到备份策略的卷包括在内。此更新包含可防止超过这些限制的其他验证。



=== SnapMirror云重新同步

此更新可确保在删除SnapMirror关系后、无法从不受支持的ONTAP版本的BlueXP  备份和恢复启动SnapMirror云重新同步。



== 2025年2月21日

此BlueXP  备份和恢复版本包含以下更新。



=== 高性能索引编制

BlueXP  备份和恢复引入了一项经过更新的索引编制功能、可提高源工作环境中数据的索引编制效率。新的索引编制功能包括更新用户界面、提高搜索和还原数据方法的性能、升级全局搜索功能以及更好的可扩展性。

以下是改进的细分：

* *文件夹整合*：更新后的版本使用包含特定标识符的名称将文件夹分组在一起，使索引编制过程更顺畅。
* *镶木地板文件缩减*：更新后的版本减少了为每个卷编制索引所使用的文件数量，从而简化了流程，并且不再需要额外的数据库。
* *通过更多会话实现横向扩展*：新版本增加了更多会话来处理索引编制任务、从而加快了处理速度。
* *支持多个索引容器*：新版本使用多个容器来更好地管理和分发索引任务。
* *拆分索引工作流*：新版本将索引编制过程分为两部分，提高了效率。
* *改进的并发性*：新版本可以同时删除或移动目录，从而加快索引编制过程。


.谁可以从该功能中受益？
所有新客户均可使用新的索引功能。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。这样、索引目录就可以跟踪每个卷和每个备份文件、从而使搜索快速高效。

在执行搜索和还原时、通过选择"启用索引"选项、在源工作环境中启用索引。

有关详细信息，请参见文档 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["如何使用搜索和恢复来恢复ONTAP数据()"]。

.支持的扩展
新的索引编制功能支持以下功能：

* 不到3分钟即可实现全局搜索效率
* 最多50亿个文件
* 每个集群最多5000个卷
* 每个卷最多10万个快照
* 基线索引编制的最长时间不超过7天。实际时间因环境而异。




=== 全局搜索性能改进

此版本还对全局搜索性能进行了增强。现在、您将看到进度指示器和更详细的搜索结果、包括文件计数和搜索所用时间。用于搜索和索引编制的专用容器可确保在五分钟内完成全局搜索。

请注意以下与全局搜索相关的注意事项：

* 不会对标记为每小时的快照执行新索引。
* 新的索引编制功能仅适用于FlexVol上的快照、不适用于FlexGroup上的快照。




== 2025年2月13日

此BlueXP  备份和恢复版本包含以下更新。



=== BlueXP backup and recovery预览版

BlueXP backup and recovery的预览版本提供了更新的用户界面，使您能够使用BlueXP backup and recovery服务中熟悉的 3-2-1 保护策略来管理 Microsoft SQL Server 工作负载。使用此新版本，您可以将这些工作负载备份到主存储，复制到辅助存储，然后备份到云对象存储。


NOTE: 本文档作为技术预览提供。对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

此版本的BlueXP backup and recovery预览版 2025 包括以下更新。

* 重新设计的用户界面为管理备份和恢复任务提供了更直观的体验。
* 预览版使您能够备份和恢复 Microsoft SQL Server 数据库。（未来版本将添加对其他工作负载的支持。）
* 此版本集成了SnapCenter功能，使您能够通过BlueXP backup and recovery用户界面使用 3-2-1 数据保护策略来管理和保护您的SnapCenter资源。
* 此版本使您能够将SnapCenter工作负载导入BlueXP backup and recovery。




== 2024年11月22日

此BlueXP  备份和恢复版本包含以下更新。



=== SnapLock Compliance和SnapLock Enterprise保护模式

现在、BlueXP  备份和恢复可以备份使用SnapLock Compliance或SnapLock Enterprise保护模式配置的FlexVol和FlexGroup内部卷。要获得此支持、集群必须运行ONTAP 9.14或更高版本。从ONTAP 9.11.1版开始、支持使用SnapLock企业模式备份FlexVol卷。早期版本的ONTAP不支持备份SnapLock保护卷。

请参见中支持的卷的完整列表 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["了解有关BlueXP备份和恢复的信息"]。



=== "卷"页面上的"搜索和还原过程索引"

在使用搜索和还原之前、您需要在要从中还原卷数据的每个源工作环境上启用"索引编制"。这样、"已创建目录"就可以跟踪每个卷的备份文件。此时、卷页面将显示索引编制状态：

* Indexed：卷已编制索引。
* 进行中
* 未为其提供过任何服务
* 索引编制已暂停
* error
* 未启用




== 2024年9月27日

此BlueXP  备份和恢复版本包含以下更新。



=== RHEL 8或9上的Podman支持以及浏览和还原功能

BlueXP  备份和恢复现在支持使用Podman引擎在Red Hat Enterprise Linux (RHEL) 8和9上还原文件和文件夹。这适用于BlueXP  备份和恢复浏览和还原方法。

BlueXP  Connector 3.9.40支持在RHEL 8或9主机上手动安装某些版本的Red Hat Enterprise Linux版本8和9，而不考虑位置以及中提到的操作系统 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主机要求"^]。这些较新的RHEL版本需要使用Podman引擎、而不是Docker引擎。以前、使用Podman引擎时、BlueXP  备份和恢复有两个限制。已删除这些限制。

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["了解有关从备份文件还原ONTAP数据的更多信息"](英文)



=== 加快目录索引编制速度可改进搜索和还原功能

此版本改进了目录索引功能、可以更快地完成基线索引编制。通过加快索引编制速度、您可以更快地使用搜索和还原功能。

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["了解有关从备份文件还原ONTAP数据的更多信息"](英文)
