---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: 了解 Cloud Backup 中的新增功能。 
---
= Cloud Backup 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 Cloud Backup 中的新增功能。



== 2022年11月2日



=== 能够将旧Snapshot副本导出到基线备份文件

如果工作环境中的卷具有与备份计划标签匹配的任何本地Snapshot副本(例如、每日、每周等)、则可以将这些历史快照作为备份文件导出到对象存储。这样、您可以通过将旧的Snapshot副本移动到基线备份副本中来初始化云中的备份。

在为您的工作环境激活Cloud Backup时、此选项可用。您也可以稍后在中更改此设置 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html["高级设置页面"]。



=== Cloud Backup现在可用于归档源系统上不再需要的卷

现在、您可以删除卷的备份关系。如果您希望停止创建新备份文件并删除源卷、但保留所有现有备份文件、则可以使用此功能提供归档机制。这样、您就可以在将来根据需要从备份文件还原卷、同时从源存储系统中清除空间。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap.html#deleting-volume-backup-relationships["了解如何操作"]。



=== 添加了支持功能、可以通过电子邮件或通知中心接收Cloud Backup警报

Cloud Backup已集成到BlueXP通知服务中。您可以通过单击BlueXP菜单栏中的通知铃来显示Cloud Backup通知。此外、您还可以将BlueXP配置为通过电子邮件发送警报通知、以便即使未登录到系统、您也可以了解重要的系统活动。可以将此电子邮件发送给需要了解备份和还原活动的任何收件人。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["了解如何操作"]。



=== 通过新的高级设置页面、您可以更改集群级别的备份设置

通过此新页面、您可以更改在为每个ONTAP 系统激活Cloud Backup时设置的多个集群级别备份设置。您还可以修改应用为"默认"备份设置的某些设置。您可以更改的一整套备份设置包括：

* 为ONTAP 系统授予访问对象存储权限的存储密钥
* 分配用于将备份上传到对象存储的网络带宽
* 未来卷的自动备份设置(和策略)
* 归档存储类(仅限AWS)
* 初始基线备份文件中是否包含历史Snapshot副本
* 是否从源系统中删除"每年"快照
* 连接到对象存储的ONTAP IP空间(如果激活期间选择不正确)


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backup-settings-ontap.html["了解有关管理集群级别备份设置的更多信息"]。



=== 现在、在使用内部部署连接器时、您可以使用搜索和还原从公有 云还原备份文件

在先前版本中、增加了在内部部署连接器时向公有 云创建备份文件的支持。在此版本中、我们仍支持在您的内部部署Connector时使用搜索和还原从Amazon S3或Azure Blob还原备份。

目前、在使用搜索和还原从Google Cloud Storage还原备份时、必须在Google Cloud Platform中部署Connector。StorageGRID 系统不支持搜索和还原-在这种情况下、您必须使用浏览和还原。



=== 已更新作业监控页面

已对进行了以下更新 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html["作业监控页面"]：

* 您可以使用"workload"列筛选页面以查看以下备份服务的作业：卷、应用程序、虚拟机和Kubernetes。
* 如果要查看特定备份作业的这些详细信息、可以为"用户名"和"作业类型"添加新列。
* "作业详细信息"页面将显示为完成主作业而正在运行的所有子作业。
* 此页面每15分钟自动刷新一次、以便您始终可以看到最新的作业状态结果。您可以单击*刷新*按钮立即更新此页面。




=== AWS跨帐户备份增强功能

如果要对Cloud Volumes ONTAP 备份使用与源卷不同的AWS帐户、则必须在BlueXP中添加目标AWS帐户凭据、并且必须将权限"S3：PutBucketPolicy"和"S3：PutBucketOwnershipControls"添加到为BlueXP提供权限的IAM角色中。过去、您需要在AWS控制台中配置许多设置、而不再需要这样做。



== 2022年9月28日



=== Cloud Backup for Applications的增强功能

* 支持Google Cloud Platform (GCP)和StorageGRID 备份应用程序一致的快照
* 创建自定义策略
* 支持归档存储
* 备份SAP HANA应用程序
* 备份VMware环境中的Oracle和SQL应用程序
* 从内部二级存储备份应用程序
* 停用备份
* 取消注册SnapCenter 服务器




=== 适用于虚拟机的Cloud Backup增强功能

* 支持StorageGRID 备份一个或多个数据存储库
* 创建自定义策略




== 2022年9月19日



=== 可以为StorageGRID 系统中的备份文件配置DataLock和勒索软件保护

上一版本针对存储在Amazon S3存储分段中的备份引入了_DataLock和勒索软件保护_。此版本扩展了对StorageGRID 系统中存储的备份文件的支持。如果集群使用的是ONTAP 9.11.1或更高版本、而StorageGRID 系统运行的是11.6.0.3或更高版本、则可以使用此新的备份策略选项。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。

请注意、您需要运行的Connector软件版本为3.9.22或更高版本。连接器必须安装在您的内部环境中、并且可以安装在可访问Internet或不可访问Internet的站点中。



=== 现在、您可以从备份文件中进行文件夹级还原

现在、如果您需要访问某个备份文件(目录或共享)中的所有文件、则可以从该文件还原该文件夹。与还原整个卷相比、还原文件夹的效率要高得多。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。此时、您只能选择和还原单个文件夹、并且只会还原该文件夹中的文件、而不会还原子文件夹或子文件夹中的文件。



=== 现在、可以从已移至归档存储的备份中进行文件级还原

过去、您只能从已移至归档存储的备份文件还原卷(仅限AWS和Azure)。现在、您可以从这些归档备份文件还原单个文件。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 现在、文件级还原提供了覆盖原始源文件的选项

过去、还原到原始卷的文件始终会作为前缀为"Restore_<file_name>"的新文件进行还原。现在、您可以选择在将源文件还原到卷上的原始位置时覆盖此源文件。此功能可用于使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 拖放以启用云备份到StorageGRID 系统

如果 https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 备份目标作为工作环境存在于Canvas上、您可以将内部ONTAP 工作环境拖动到目标上以启动Cloud Backup设置向导。



== 2022年8月18日



=== 添加了保护Cloud原生 应用程序数据的支持

Cloud Backup for Applications是一种基于SaaS的服务、可为在NetApp Cloud Storage上运行的应用程序提供数据保护功能。在BlueXP中启用的适用于应用程序的云备份可为驻留在Amazon FSX for NetApp ONTAP 上的Oracle数据库提供高效、一致且基于策略的备份和还原。https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html["了解更多信息。"^]。



=== 现在、Azure Blob中的备份文件支持搜索和还原

现在、将备份文件存储在Azure Blob存储中的用户可以使用"搜索和还原"方法还原卷和文件。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["请参见如何使用搜索和放大器还原卷和文件"^]。

请注意、要使用此功能、需要在Connector角色中添加其他权限。使用3.9.21版软件(2022年8月)部署的Connector包含这些权限。如果您使用早期版本部署了Connector、则需要手动添加权限。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["如有必要、请参见如何添加这些权限"^]。



=== 我们增加了保护备份文件免遭删除和勒索软件攻击的功能

Cloud Backup现在支持对象锁定、用于进行勒索软件安全备份。如果您的集群使用的是ONTAP 9.11.1或更高版本、而您的备份目标是Amazon S3、则现在可以使用一个名为_DataLock和勒索软件保护_的新备份策略选项。DataLock可防止您的备份文件被修改或删除、勒索软件保护功能会扫描您的备份文件、以查找您的备份文件遭到勒索软件攻击的证据。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。

请注意、要使用此功能、需要在Connector角色中添加其他权限。使用3.9.21版软件部署的Connector包含这些权限。如果您使用早期版本部署了Connector、则需要手动添加权限。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions["如有必要、请参见如何添加这些权限"^]。



=== Cloud Backup现在支持使用自定义SnapMirror标签创建的策略

以前、Cloud Backup仅支持预定义的SnapMirror标签、例如每小时、每天、每周、每小时和每年。现在、Cloud Backup可以发现包含您使用System Manager或CLI创建的自定义SnapMirror标签的SnapMirror策略。这些新标签会显示在Cloud Backup UI中、您可以使用所选的SnapMirror标签将卷备份到云中。



=== 对ONTAP 系统的备份策略进行了更多改进

某些备份策略页面经过重新设计、可以更轻松地查看每个ONTAP 集群中的卷可用的所有备份策略。这样可以更轻松地查看可用策略的详细信息、以便您可以在卷上应用最佳策略。



=== 拖放以启用Cloud Backup to Azure Blob和Google Cloud Storage

如果 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html["Azure Blob"^] 或 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html["Google Cloud 存储"^] 备份目标作为工作环境存在于Canvas上、您可以将本地ONTAP 或Cloud Volumes ONTAP 工作环境(安装在Azure或GCP中)拖动到目标上以启动备份设置向导。

Amazon S3存储分段已具有此功能。



== 2022年7月13日



=== 添加了对备份SnapLock 企业卷的支持

现在、您可以使用云备份将SnapLock 企业卷备份到公有 和私有云。此功能要求您的ONTAP 系统运行的是ONTAP 9.11.1或更高版本。但是、目前不支持SnapLock 合规性卷。



=== 现在、您可以在使用内部部署连接器时在公有 云中创建备份文件

过去、您需要将Connector部署在与创建备份文件相同的云提供商中。现在、您可以使用内部部署的Connector创建备份文件、将本地ONTAP 系统备份到Amazon S3、Azure Blob和Google云存储。(在StorageGRID 系统上创建备份文件时、始终需要使用内部连接器。)



=== 在为ONTAP 系统创建备份策略时、还可以使用其他功能

* 现在可以按年计划进行备份。对于年度备份、默认保留值为1、但如果要访问前几年的许多备份文件、您可以更改此值。
* 您可以为备份策略命名、以便使用更具描述性的文本来标识策略。




== 2022年6月14日



=== 增加了对在无法访问Internet的站点中备份内部ONTAP 集群数据的支持

如果您的内部ONTAP 集群位于无法访问Internet的站点中、也称为非公开站点或脱机站点、则现在您可以使用Cloud Backup将卷数据备份到同一站点中的NetApp StorageGRID 系统。此功能还要求在脱机站点中部署BlueXP Connector (3.9.19或更高版本)。

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["请参见如何在脱机站点中安装Connector"]。https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html["了解如何将ONTAP 数据备份到脱机站点中的StorageGRID"]。



=== 适用于虚拟机的Cloud Backup 1.1.0现已正式上市

您可以通过将适用于VMware vSphere的SnapCenter 插件与BlueXP集成来保护虚拟机上的数据。您可以将数据存储库备份到云、并将虚拟机轻松还原回适用于VMware vSphere的内部部署SnapCenter 插件。

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html["了解有关保护虚拟机到云的更多信息"]。



=== ONTAP 浏览和还原功能不需要云还原实例

以前从S3和Blob存储执行文件级浏览和还原操作需要一个单独的Cloud Restore实例/虚拟机。此实例在不使用时关闭、但在还原文件时仍会增加一些时间和成本。此功能已被一个免费容器所取代、此容器可在需要时部署在Connector上。它具有以下优势：

* 文件级还原操作不会增加成本
* 文件级还原操作速度更快
* 支持在内部安装Connector时从云中对文件执行浏览和还原操作


请注意、如果您先前使用了Cloud Restore实例/VM、则该实例/VM将自动删除。Cloud Backup进程将每天运行一次、以删除所有旧的Cloud Restore实例。此更改是完全透明的—不会对数据产生任何影响、您也不会注意到备份或还原作业发生了任何更改。



=== 浏览并还原对Google Cloud和StorageGRID 存储中文件的支持

现在、通过添加用于浏览和还原操作的容器(如上所述)、可以从存储在Google Cloud和StorageGRID 系统中的备份文件执行文件还原操作。现在、浏览和还原可用于在所有公有 云提供商之间以及从StorageGRID 还原文件。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["请参见如何使用浏览和放大功能；还原ONTAP 备份中的卷和文件"]。



=== 拖放以启用Cloud Backup到S3存储

如果用于备份的Amazon S3目标作为工作环境存在于Canvas上、则可以将本地ONTAP 集群或Cloud Volumes ONTAP 系统(安装在AWS中)拖动到Amazon S3工作环境中以启动设置向导。



=== 自动将备份策略应用于Kubernetes集群中新创建的卷

如果您在激活Cloud Backup后向Kubernetes集群添加了新的永久性卷、则在过去、您需要记住为这些卷配置备份。现在、您可以选择将自动应用于新创建的卷的策略 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["从_Backup Settings_页面"] 适用于已激活Cloud Backup的集群。



=== Cloud Backup API现在可用于管理备份和还原操作

这些API可从获取 https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html[]。请参见 link:api-backup-restore.html["此页面"] 有关API的概述。



== 2022年5月2日



=== 现在、Google Cloud Storage中的备份文件支持搜索和还原

4月份、在AWS中存储备份文件的用户开始使用"搜索和还原"方法来还原卷和文件。现在、将备份文件存储在Google Cloud Storage中的用户可以使用此功能。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["请参见如何使用搜索和放大器还原卷和文件"]。



=== 配置要自动应用于Kubernetes集群中新创建的卷的备份策略

如果您在激活Cloud Backup后向Kubernetes集群添加了新的永久性卷、则在过去、您需要记住为这些卷配置备份。现在、您可以选择将自动应用于新创建的卷的策略。在为新Kubernetes集群激活Cloud Backup时、此选项可在设置向导中使用。



=== Cloud Backup现在需要获得许可证、才能在工作环境中激活

在Cloud Backup中实施许可的方式方面、有一些变化：

* 您必须先从云提供商处注册PAYGO Marketplace订阅、或者从NetApp购买BYOL许可证、然后才能激活Cloud Backup。
* 30天免费试用版仅在使用云提供商提供的PAYGO订阅时可用、而在使用BYOL许可证时不可用。
* 免费试用从Marketplace订阅开始的那一天开始。例如、如果在对Cloud Volumes ONTAP 系统使用Marketplace订阅30天之后激活免费试用、则Cloud Backup试用将不可用。


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html["详细了解可用的许可模式"]。



== 2022 年 4 月 4 日



=== 适用于应用程序的 Cloud Backup 1.1.0 （由 SnapCenter 提供支持）现已正式上市

通过全新的Cloud Backup for Applications功能、您可以将适用于Oracle和Microsoft SQL的现有应用程序一致性快照(备份)从内部主存储卸载到Amazon S3或Azure Blob中的云对象存储。

如果需要，您可以将此数据从云还原到内部环境。

link:concept-protect-app-data-to-cloud.html["了解有关保护内部应用程序数据到云的更多信息"]。



=== 新的搜索和还原功能可在所有 ONTAP 备份文件中搜索卷或文件

现在，您可以按部分或完整卷名称，部分或完整文件名称，大小范围以及其他搜索筛选器在 * 所有 ONTAP 备份文件 * 中搜索卷或文件。如果您不确定哪个集群或卷是数据源，这是一种很好的新方法来查找要还原的数据。 link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["了解如何使用搜索和放大；还原"]。



== 2022 年 3 月 3 日



=== 能够将永久性卷从 GKEKubernetes 集群备份到 Google Cloud 存储

如果您的 GKE 集群安装了 NetApp Astra Trident ，并且使用适用于 GCP 的 Cloud Volumes ONTAP 作为集群的后端存储，则可以将永久性卷备份到 Google Cloud 存储或从 Google Cloud 存储还原。 link:task-backup-kubernetes-to-gcp.html["有关详细信息，请访问此处"]。



=== 此版本已停止使用 Cloud Data sense 扫描 Cloud Backup 文件的测试版功能



== 2022 年 2 月 14 日



=== 现在，您可以将备份策略分配给单个集群中的各个卷

过去，您只能为集群中的所有卷分配一个备份策略。现在，您可以为一个集群创建多个备份策略，并将不同的策略应用于不同的卷。 link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["请参见如何为集群创建新的备份策略并将其分配给选定卷"]。



=== 通过一个新选项，您可以自动将默认备份策略应用于新创建的卷

过去，激活 Cloud Backup 后在工作环境中创建的新卷要求您手动应用备份策略。现在、无论卷是在BlueXP、System Manager、CLI中创建的、还是使用API创建的、Cloud Backup都将发现卷并应用您选择作为默认策略的备份策略。

如果在新的工作环境中启用备份，或者从 _Manage Volumes_ 页面为现有工作环境启用备份，则可以使用此选项。



=== 新的作业监控器可用于查看所有备份和还原作业的正在处理状态

如果您对多个卷启动了操作，例如更改备份策略或删除备份，则作业监控器会非常有用，这样您可以查看操作何时在所有卷上完成。 link:task-monitor-backup-jobs.html["请参见如何使用作业监控器"]。



== 2022 年 1 月 2 日



=== 能够将永久性卷从 AKS Kubernetes 集群备份到 Azure Blob 存储

如果您的 AKS 集群安装了 NetApp Astra Trident ，并且使用适用于 Azure 的 Cloud Volumes ONTAP 作为集群的后端存储，则可以将卷备份到 Azure Blob 存储以及从 Azure Blob 存储还原卷。 link:task-backup-kubernetes-to-azure.html["有关详细信息，请访问此处"]。



=== 此版本中更改了 Cloud Backup Service 费用，以便与行业标准更加一致

现在，您无需根据备份文件的大小为 NetApp 支付容量费用，而是仅为所保护的数据付费，该数据是通过要备份的源 ONTAP 卷的逻辑已用容量（在 ONTAP 效率之前）计算得出的。此容量也称为前端 TB （前端 TB ）。



== 2021 年 11 月 28 日



=== 能够将 EKS Kubernetes 集群中的永久性卷备份到 Amazon S3

如果您的 EKS 集群安装了 NetApp Astra Trident ，并且使用 Cloud Volumes ONTAP for AWS 作为集群的后端存储，则可以将卷备份到 Amazon S3 或从 Amazon S3 还原卷。 link:task-backup-kubernetes-to-s3.html["有关详细信息，请访问此处"]。



=== 用于备份 DP 卷的增强功能

现在， Cloud Backup 支持为 SVM-DR 关系中目标 ONTAP 系统上的 DP 卷创建备份。存在一些限制，请参见 link:concept-ontap-backup-to-cloud.html#limitations["限制"] 了解详细信息。



== 2021 年 11 月 5 日



=== 可以在将卷还原到内部 ONTAP 系统时选择专用端点

从 Amazon S3 或 Azure Blob 上的备份文件将卷还原到内部 ONTAP 系统时，现在您可以选择一个私有端点，用于以私密方式安全地连接到内部系统。



=== 现在，您可以在数天后将旧备份文件分层到归档存储，以节省成本

如果集群运行的是 ONTAP 9.10.1 或更高版本，而您使用的是 AWS 或 Azure 云存储，则可以将备份分层到归档存储。请参见有关的详细信息 link:reference-aws-backup-tiers.html["AWS S3 归档存储类"] 和 link:reference-azure-backup-tiers.html["Azure Blob 归档访问层"]。



=== Cloud Backup BYOL 许可证已移至 " 数字电子钱包 " 中的 " 数据服务许可证 " 选项卡

Cloud Backup的BYOL许可已从Cloud Backup Licenses选项卡移至BlueXP Digital Wallet中的Data Services Licenses选项卡。



== 2021 年 10 月 4 日



=== 现在，在执行卷或文件还原时，备份文件大小将显示在备份页面中

如果您要删除不必要的大型备份文件，或者您可以比较备份文件大小，以确定可能因恶意软件攻击而导致的任何异常备份文件，则此功能非常有用。



=== TCO 计算器可用于比较 Cloud Backup 成本

总拥有成本计算器可帮助您了解 Cloud Backup 的总拥有成本，并将这些成本与传统备份解决方案进行比较，并估算潜在节省量。请查看https://cloud.netapp.com/cloud-backup-service-tco-calculator["此处"^]。



=== 能够为工作环境取消注册 Cloud Backup

现在，您可以轻松地完成这项工作 link:task_manage_backups.html#unregistering-cloud-backup-for-a-working-environment["为工作环境取消注册 Cloud Backup"] 如果您不想再对该工作环境使用备份功能（或需要付费），
