---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: 了解BlueXP备份和恢复的新增功能。 
---
= BlueXP 备份和恢复的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP备份和恢复的新增功能。



== 2025 年 6 月 9 日

此BlueXP  备份和恢复版本包含以下更新。



=== 索引目录支持更新

2025 年 2 月，我们推出了更新的索引功能（索引目录 v2），您可以在“搜索和还原”数据还原方法中使用此功能。上一版本显著提升了本地环境中的数据索引性能。在此版本中，索引目录现已可在 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 环境中使用。

如果您是新客户，所有新环境均默认启用索引目录 v2。如果您是现有客户，您可以重新索引您的环境以利用索引目录 v2。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。执行搜索和恢复时，选择“*启用索引*”选项。

索引目录可以跟踪每个卷和备份文件，使您的搜索快速而高效。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜索和恢复来恢复ONTAP数据()"]。



=== Azure 专用链接终结点和服务终结点

通常，BlueXP 备份和恢复会与云提供商建立私有端点，以处理各种保护任务。此版本引入了一项可选设置，可让您启用或禁用 BlueXP 备份和恢复自动创建私有端点的功能。如果您希望更好地控制私有端点的创建过程，这项设置可能会对您有所帮助。

您可以在启用保护或开始恢复过程时启用或禁用此选项。

如果禁用此设置，则必须手动创建专用端点，以确保 BlueXP 备份和恢复功能正常运行。如果没有正确的连接，您可能无法成功执行备份和恢复任务。



=== ONTAP S3 上支持 SnapMirror 到云重新同步

上一版本引入了对 SnapMirror 到云重新同步 (SM-C Resync) 的支持。该功能简化了 NetApp 环境中卷迁移期间的数据保护。此版本增加了对 ONTAP S3 以及其他兼容 S3 的提供商（例如 Wasabi 和 MinIO）上的 SM-C Resync 的支持。



=== 为 StorageGRID 带来您自己的存储桶

当您在对象存储中为工作环境创建备份文件时，BlueXP 备份和恢复功能会默认在您配置的对象存储帐户中为备份文件创建容器（存储桶或存储帐户）。之前，您可以覆盖此设置，并为 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。在此版本中，您现在可以自带 StorageGRID 对象存储容器。

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["创建您自己的对象存储容器"]



== 2025年5月13日

此BlueXP  备份和恢复版本包含以下更新。



=== SnapMirror到云重新同步以进行卷迁移

SnapMirror到云重新同步功能可简化NetApp环境中卷迁移期间的数据保护和连续性。使用SnapMirror逻辑复制(LRSE)将卷迁移到内部NetApp部署或Cloud Volumes ONTAP或Cloud Volumes Service等基于云的解决方案时、SnapMirror到云重新同步可确保现有云备份保持完好且正常运行。

此功能无需执行耗时且资源密集型的重新基线操作、从而可以在迁移后继续执行备份操作。此功能在工作负载迁移方案中非常有用、可同时支持FlexVol和FlexGroup、并可从ONTAP 9.161版开始使用。

通过在不同环境之间保持备份连续性、SnapMirror到云重新同步可提高运营效率、并降低混合云和多云数据管理的复杂性。

有关如何执行重新同步操作的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["使用SnapMirror迁移卷到云重新同步"]。



=== 支持第三方MinIO对象存储(预览)

BlueXP  备份和恢复现在将其支持扩展到第三方对象存储、并主要侧重于MinIO。通过这一新的预览功能、您可以利用任何与S3兼容的对象存储来满足备份和恢复需求。

在此预览版本中、我们希望确保在推出完整功能之前与第三方对象存储实现强大集成。我们鼓励您探索这项新功能、并提供反馈以帮助改进服务。


IMPORTANT: 此功能不应在生产环境中使用。

*预览模式限制*

在预览此功能时、存在一些限制：

* 不支持自带存储分段(BYOB)。
* 不支持在策略中启用DataLock。
* 不支持在策略中启用归位模式。
* 仅支持内部ONTAP环境。
* 不支持MetroCluster。
* 不支持用于启用存储分段级别加密的选项。


* 入门 *

要开始使用此预览功能、您必须在BlueXP  连接器上启用一个标志。然后、您可以通过在备份部分中选择*第三方兼容*对象存储、在保护工作流中输入您的Minio第三方对象存储的连接详细信息。

有关如何启用预览功能的说明，请参阅 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["在BlueXP  备份和恢复中启用预览功能"]。



== 2025年4月16日

此BlueXP  备份和恢复版本包含以下更新。



=== UI改进

此版本通过简化界面增强了用户体验：

* 在V2信息板的卷表中、从卷表中删除聚合列以及Snapshot策略、备份策略和复制策略列后、布局将更加简化。
* 从下拉列表中排除未激活的工作环境可减少界面的干扰、提高导航效率并加快加载速度。
* 禁用标记列排序后、您仍可查看标记、以确保重要信息始终易于访问。
* 去除保护图标上的标签有助于使外观更清晰、并减少加载时间。
* 在工作环境激活过程中、对话框会显示一个加载图标、以提供反馈、直到发现过程完成、从而提高系统操作的透明度和可信度。




=== 增强的卷信息板(预览)

现在、卷信息板加载时间不到10秒、从而提供了一个速度更快、效率更高的界面。此预览版可供部分客户使用、让他们可以及早了解这些改进。



=== 支持第三方芥末对象存储(预览)

BlueXP  备份和恢复现在将其支持扩展到第三方对象存储、主要侧重于芥末。通过这一新的预览功能、您可以利用任何与S3兼容的对象存储来满足备份和恢复需求。



==== 开始使用芥末

要开始使用第三方存储作为对象存储、必须在BlueXP  连接器中启用一个标志。然后、您可以输入第三方对象存储的连接详细信息、并将其集成到备份和恢复工作流中。

.步骤
. 通过SSH连接到您的连接器。
. 转到BlueXP  备份和恢复CBS服务器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 通过VIM或任何其他编辑器打开 `default.json`文件夹中的文件 `config`：
+
[listing]
----
vi default.json
----
. 修改 `allow-s3-compatible`：false到 `allow-s3-compatible`：true。
. 保存更改。
. 退出容器。
. 重新启动BlueXP  备份和恢复CBS服务器容器。


.结果
重新打开容器后、打开BlueXP  备份和恢复UI。启动备份或编辑备份策略时、您将看到新的提供程序"S3兼容"与AWS、Microsoft Azure、Google Cloud、StorageGRID和ONTAP S3的其他备份提供程序一起列出。



==== 预览模式限制

在预览此功能时、请考虑以下限制：

* 不支持自带存储分段(BYOB)。
* 不支持在策略中启用DataLock。
* 不支持在策略中启用归份模式。
* 仅支持内部ONTAP环境。
* 不支持MetroCluster。
* 不支持用于启用存储分段级别加密的选项。


在此预览期间、我们建议您探索这一新功能、并在推出完整功能之前提供有关与第三方对象存储集成的反馈。



== 2025年3月17日

此BlueXP  备份和恢复版本包含以下更新。



=== SMB快照浏览

此BlueXP  备份和恢复更新解决了客户无法在SMB环境中浏览本地快照的问题。



=== AWS GovCloud环境更新

此BlueXP  备份和恢复更新修复了由于TLS证书错误而导致UI无法连接到AWS GovCloud环境的问题。已使用BlueXP  连接器主机名而非IP地址解决此问题。



=== 备份策略保留限制

以前、BlueXP  备份和恢复用户界面会将备份限制为999个副本、而命令行界面则允许更多副本。现在、您最多可以将4、000个卷连接到一个备份策略、并将1、018个未连接到备份策略的卷包括在内。此更新包含可防止超过这些限制的其他验证。



=== SnapMirror云重新同步

此更新可确保在删除SnapMirror关系后、无法从不受支持的ONTAP版本的BlueXP  备份和恢复启动SnapMirror云重新同步。



== 2025年2月21日

此BlueXP  备份和恢复版本包含以下更新。



=== 高性能索引编制

BlueXP  备份和恢复引入了一项经过更新的索引编制功能、可提高源工作环境中数据的索引编制效率。新的索引编制功能包括更新用户界面、提高搜索和还原数据方法的性能、升级全局搜索功能以及更好的可扩展性。

以下是改进的细分：

* *文件夹整合*：更新后的版本使用包含特定标识符的名称将文件夹分组在一起，使索引编制过程更顺畅。
* *镶木地板文件缩减*：更新后的版本减少了为每个卷编制索引所使用的文件数量，从而简化了流程，并且不再需要额外的数据库。
* *通过更多会话实现横向扩展*：新版本增加了更多会话来处理索引编制任务、从而加快了处理速度。
* *支持多个索引容器*：新版本使用多个容器来更好地管理和分发索引任务。
* *拆分索引工作流*：新版本将索引编制过程分为两部分，提高了效率。
* *改进的并发性*：新版本可以同时删除或移动目录，从而加快索引编制过程。


.谁可以从该功能中受益？
所有新客户均可使用新的索引功能。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。这样、索引目录就可以跟踪每个卷和每个备份文件、从而使搜索快速高效。

在执行搜索和还原时、通过选择"启用索引"选项、在源工作环境中启用索引。

有关详细信息，请参见文档 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜索和恢复来恢复ONTAP数据()"]。

.支持的扩展
新的索引编制功能支持以下功能：

* 不到3分钟即可实现全局搜索效率
* 最多50亿个文件
* 每个集群最多5000个卷
* 每个卷最多10万个快照
* 基线索引编制的最长时间不超过7天。实际时间因环境而异。




=== 全局搜索性能改进

此版本还对全局搜索性能进行了增强。现在、您将看到进度指示器和更详细的搜索结果、包括文件计数和搜索所用时间。用于搜索和索引编制的专用容器可确保在五分钟内完成全局搜索。

请注意以下与全局搜索相关的注意事项：

* 不会对标记为每小时的快照执行新索引。
* 新的索引编制功能仅适用于FlexVol上的快照、不适用于FlexGroup上的快照。




== 2024年11月22日

此BlueXP  备份和恢复版本包含以下更新。



=== SnapLock Compliance和SnapLock Enterprise保护模式

现在、BlueXP  备份和恢复可以备份使用SnapLock Compliance或SnapLock Enterprise保护模式配置的FlexVol和FlexGroup内部卷。要获得此支持、集群必须运行ONTAP 9.14或更高版本。从ONTAP 9.11.1版开始、支持使用SnapLock企业模式备份FlexVol卷。早期版本的ONTAP不支持备份SnapLock保护卷。

请参见中支持的卷的完整列表 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["了解有关BlueXP备份和恢复的信息"]。



=== "卷"页面上的"搜索和还原过程索引"

在使用搜索和还原之前、您需要在要从中还原卷数据的每个源工作环境上启用"索引编制"。这样、"已创建目录"就可以跟踪每个卷的备份文件。此时、卷页面将显示索引编制状态：

* Indexed：卷已编制索引。
* 进行中
* 未为其提供过任何服务
* 索引编制已暂停
* error
* 未启用




== 2024年9月27日

此BlueXP  备份和恢复版本包含以下更新。



=== RHEL 8或9上的Podman支持以及浏览和还原功能

BlueXP  备份和恢复现在支持使用Podman引擎在Red Hat Enterprise Linux (RHEL) 8和9上还原文件和文件夹。这适用于BlueXP  备份和恢复浏览和还原方法。

BlueXP  Connector 3.9.40支持在RHEL 8或9主机上手动安装某些版本的Red Hat Enterprise Linux版本8和9，而不考虑位置以及中提到的操作系统 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主机要求"^]。这些较新的RHEL版本需要使用Podman引擎、而不是Docker引擎。以前、使用Podman引擎时、BlueXP  备份和恢复有两个限制。已删除这些限制。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["了解有关从备份文件还原ONTAP数据的更多信息"](英文)



=== 加快目录索引编制速度可改进搜索和还原功能

此版本改进了目录索引功能、可以更快地完成基线索引编制。通过加快索引编制速度、您可以更快地使用搜索和还原功能。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["了解有关从备份文件还原ONTAP数据的更多信息"](英文)



== 2024年7月22日



=== 还原小于1 GB的卷

在此版本中、您现在可以还原在ONTAP中创建的小于1 GB的卷。可以使用ONTAP创建的最小卷大小为20 MB。



=== 有关如何降低DataLock成本的提示

DataLock功能可保护备份文件、使其在指定时间段内不会被修改或删除。这有助于保护文件免受勒索软件攻击。

有关DataLock的详细信息以及有关如何降低相关成本的提示，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["备份到对象策略设置"]。



=== AWS IAM角色无处不在集成

通过Amazon Web Services (AWS)身份和访问管理(IAM)角色无处不在服务、您可以对AWS的_Outside _工作负载使用IAM角色和短期凭据来安全地访问AWS API、就像对Workloads_on_ AWS使用IAM角色一样。当您在任意位置使用IAM角色时、私有密钥基础架构和AWS令牌不需要长期AWS访问密钥和机密密钥。这样、您可以更频繁地轮换凭据、从而提高安全性。

在此版本中、对AWS IAM角色无处不在服务的支持只是一项技术预览。

请参阅 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP备份和恢复2024年7月发布博客"]。



=== FlexGroup文件夹或目录还原现在可用

以前、可以还原FlexVol卷、但无法还原FlexGroup文件夹或目录。对于ONTAP 9.15.1P2、您可以使用浏览并还原选项还原FlexGroup文件夹。

在此版本中、对FlexGroup文件夹还原的支持是一项技术预览。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["使用浏览和放大功能还原文件夹和文件；还原"]。

有关手动启用的详细信息，请参见 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXP备份和恢复2024年7月发布博客"]。



== 2024年5月17日



=== 对内部连接器使用RHEL 8和RHEL 9时的限制

对于在RHEL 8或9主机上手动安装Connector软件的任何操作、BlueXP Connector 3.9.40支持Red Hat Enterprise Linux版本8和9的某些版本、而不考虑中所述的操作系统位于何处 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["主机要求"^]。这些较新的RHEL版本需要使用Podman引擎、而不是Docker引擎。目前、使用Podman引擎时、BlueXP备份和恢复存在两个限制。

请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["备份和还原限制"] 了解详细信息。

以下过程包括新的Podman说明：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["重新启动BlueXP备份和恢复"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["在非公开站点中还原BlueXP备份和恢复数据"]




== 2024年4月30日



=== 能够启用或禁用计划内勒索软件扫描

以前、您可以启用或禁用勒索软件扫描、但无法对计划扫描执行此操作。

在此版本中、您现在可以使用"高级设置"页面上的选项对最新Snapshot副本启用或禁用计划内勒索软件扫描。如果启用此功能、则默认情况下每周执行一次扫描。您可以将该计划更改为天数或周数、也可以将其禁用、从而节省成本。

有关详细信息、请参见以下信息：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["管理备份设置"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["管理ONTAP卷的策略"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["备份到对象策略设置"]




== 2024年4月4日



=== 能够启用或禁用勒索软件扫描

以前、如果在备份策略中启用了勒索软件检测、则在创建第一个备份和还原备份时会自动进行扫描。以前、该服务会扫描所有Snapshot副本、您无法禁用这些扫描。

在此版本中、您现在可以使用"高级设置"页面上的选项对最新Snapshot副本启用或禁用勒索软件扫描。如果启用此功能、则默认情况下每周执行一次扫描。

有关详细信息、请参见以下信息：

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["管理备份设置"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["管理ONTAP卷的策略"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["备份到对象策略设置"]


ifdef::aws[]

请参阅 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"]和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["将Cloud Volumes ONTAP 数据备份到Azure Blob"]。

endif::aws[]



== 2024年3月12日



=== 能够从云备份"快速还原"到内部ONTAP卷

现在、您可以将卷从云存储快速还原到内部ONTAP目标卷。以前、您只能快速还原到Cloud Volumes ONTAP系统。快速还原非常适合需要尽快提供对卷的访问权限的灾难恢复情形。快速还原比完整卷还原速度快得多；它会将元数据从云快照还原到ONTAP目标卷。源可能来自AWS S3、Azure Blb、Google云服务或NetApp StorageGRID。

内部ONTAP目标系统必须运行ONTAP 9.14.1或更高版本。

您可以使用浏览和还原过程执行此操作、而不是使用搜索和还原过程。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["从备份文件还原ONTAP数据"]。



=== 能够从Snapshot和复制副本还原文件和文件夹

以前、您只能从AWS、Azure和Google Cloud Services中的备份副本还原文件和文件夹。现在、您可以从本地Snapshot副本和复制副本还原文件和文件夹。

您可以使用搜索和还原过程执行此功能、而不是使用浏览和还原过程。



== 2024年2月1日



=== 对虚拟机的BlueXP备份和恢复进行了增强

* 支持将虚拟机还原到备用位置
* 支持取消数据存储库保护




== 2023年12月15日



=== 可用于本地Snapshot和复制Snapshot副本的报告

以前、您只能对备份副本生成报告。现在、您还可以创建有关本地Snapshot副本和复制Snapshot副本的报告。

通过这些报告、您可以执行以下操作：

* 确保根据组织策略保护关键数据。
* 确保一组卷的备份运行顺畅。
* 为生产数据提供保护证明。


请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["关于数据保护覆盖范围的报告"]。



=== 卷上提供了自定义标记、用于排序和筛选

现在、您可以从ONTAP 9.13.1开始为卷添加自定义标记、以便可以在工作环境内和工作环境之间将卷分组在一起。这样、您就可以在BlueXP备份和恢复UI页面中对卷进行排序并在报告中进行筛选。



=== 目录备份保留30天

以前、Catalog.zip备份会保留7天。现在、它们会保留30天。

请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["在非公开站点中还原BlueXP备份和恢复数据"]。



== 2023年10月23日



=== 在备份激活期间创建3-2-1备份策略

以前、必须在启动Snapshot、复制或备份之前创建自定义策略。现在、您可以使用BlueXP备份和恢复UI在备份激活过程中创建策略。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["详细了解策略"]。



=== 支持按需快速还原ONTAP卷

现在、通过BlueXP备份和恢复、可以将卷从云存储"快速还原"到Cloud Volumes ONTAP系统。快速还原非常适合需要尽快提供对卷的访问权限的灾难恢复情形。快速还原会将元数据从备份文件还原到卷、而不是还原整个备份文件。

Cloud Volumes ONTAP目标系统必须运行ONTAP 9.13.0或更高版本。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["了解有关还原数据的更多信息"]。

BlueXP备份和恢复作业监控器还会显示有关快速恢复作业进度的信息。



=== 支持在作业监控器中计划作业

BlueXP备份和恢复作业监控器以前会监控计划的卷到对象存储备份和还原作业、但不会监控通过UI或API计划的本地Snapshot、复制、备份和还原作业。

BlueXP备份和恢复作业监控器现在包括本地快照、复制以及对象存储备份的计划作业。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["了解有关更新的作业监控器的更多信息"]。



== 2023年10月13日



=== 增强了适用于应用程序的BlueXP备份和恢复功能(云原生)

* Microsoft SQL Server数据库
+
** 支持备份、还原和恢复Amazon FSx for NetApp ONTAP上的Microsoft SQL Server数据库
** 只有通过REST API才支持所有操作。


* SAP HANA系统
+
** 在系统刷新期间、系统会使用工作流(而不是脚本)自动挂载和卸载卷
** 支持添加、删除、编辑、删除、维护、 并使用UI升级插件主机






=== 针对应用程序的BlueXP备份和恢复增强功能(混合)

* 支持数据锁定和勒索软件保护
* 支持将备份从StorageGRID移至归档层
* 支持将MongoDB、MySQL和PostgreSQL应用程序数据从内部ONTAP系统备份到Amazon Web Services、Microsoft Azure、Google云平台和StorageGRID。您可以根据需要还原数据。




=== 对虚拟机的BlueXP备份和恢复进行了增强

* 支持Connector代理部署模式




== 2023年9月11日



=== 为ONTAP数据提供新的策略管理

此版本支持在用户界面中创建自定义Snapshot策略、复制策略以及用于将ONTAP数据备份到对象存储的策略。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["详细了解策略"]。



=== 支持从ONTAP S3对象存储中的卷还原文件和文件夹

以前、如果将卷备份到ONTAP S3对象存储、则无法使用"浏览和还原"功能还原文件和文件夹。此版本取消了此限制。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["了解有关还原数据的更多信息"]。



=== 能够立即归档备份数据、而不是先写入标准存储

现在、您可以立即将备份文件发送到归档存储、而无需将数据写入标准云存储。对于很少需要从云备份访问数据的用户或要将备份替换为磁带环境的用户来说、这一点尤其有用。



=== 为备份和还原SnapLock卷提供了更多支持

现在、备份和恢复可以备份使用SnapLock Enterprise保护模式配置的FlexVol和FlexGroup卷。要获得此支持、集群必须运行ONTAP 9.14或更高版本。从ONTAP 9.11.1版开始、支持使用SnapLock企业模式备份FlexVol卷。早期版本的ONTAP不支持备份SnapLock保护卷。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["了解有关保护ONTAP数据的更多信息"]。



== 2023年8月1日

[IMPORTANT]
====
* 由于增强了安全性、您的Connector现在需要通过出站Internet访问其他端点、以便在公有云环境中管理备份和恢复资源。如果此端点尚未添加到防火墙的"允许"列表中、您将在UI中看到有关"服务不可用"或"无法确定服务状态"的错误：
+
\https://netapp-cloud-account.auth0.com

* 现在、如果您使用的是"CVO专业版"软件包、可以将Cloud Volumes ONTAP和BlueXP备份和恢复捆绑在一起、则需要订阅备份和恢复PAYGO。过去不需要这样做。符合条件的Cloud Volumes ONTAP系统的备份和恢复订阅不会产生任何费用、但在任何新卷上配置备份时需要此费用。


====


=== 添加了将卷备份到S3配置的ONTAP系统上的分段的支持

现在、您可以使用已配置简单存储服务(S3)的ONTAP系统将卷备份到对象存储。内部ONTAP系统和Cloud Volumes ONTAP系统均支持此功能。在云部署和不能访问Internet的内部位置("私有"模式部署)支持此配置。

ifdef::aws[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["了解更多信息。"]。

endif::aws[]



=== 现在、您可以将受保护卷中的现有Snapshot包含在备份文件中

过去、您可以将读写卷中的现有Snapshot副本包含在初始备份文件中并存储到对象存储中(而不是从最新的Snapshot副本开始)。只读卷(数据保护卷)中的现有Snapshot副本不包含在此备份文件中。现在、您可以选择在"DP"卷的备份文件中包含较早的Snapshot副本。

备份向导会在备份步骤结束时显示一条提示、您可以在其中选择这些"现有快照"。



=== BlueXP备份和恢复不再支持对未来添加的卷进行自动备份

以前、您可以选中备份向导中的复选框、将选定备份策略应用于添加到集群中的所有未来卷。根据用户反馈以及未使用此功能、此功能已被删除。您需要手动为添加到集群中的任何新卷启用备份。



=== "作业监控"页面已更新、新增了一些功能

现在、"作业监控"页面提供了与3-2-1备份策略相关的详细信息。该服务还提供与备份策略相关的其他警报通知。

"备份生命周期"类型筛选器已重命名为"保留"。使用此筛选器可跟踪备份生命周期并确定所有备份副本的到期日期。"保留"作业类型会捕获在受BlueXP备份和恢复保护的卷上启动的所有Snapshot删除作业。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["了解有关更新的作业监控器的更多信息"]。



== 2023年7月6日



=== BlueXP备份和恢复现在可以计划和创建Snapshot副本以及复制的卷

BlueXP备份和恢复现在支持您实施3-2-1策略、在2个不同的存储系统上拥有3个源数据副本、在云中拥有1个副本。激活后、您将获得：

* 源系统上卷的Snapshot副本
* 复制的卷位于其他存储系统上
* 备份对象存储中的卷


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["详细了解全新的全频谱备份和还原功能"]。

这一新功能也是适用场景恢复操作。您可以从Snapshot副本、复制的卷或云中的备份文件执行还原操作。这样、您可以灵活地选择满足恢复要求的备份文件、包括恢复成本和速度。

请注意、只有运行ONTAP 9.8或更高版本的集群才支持此新功能和用户界面。如果集群使用的是早期版本的软件、则可以继续使用先前版本的BlueXP备份和恢复。但是、我们建议您升级到受支持的ONTAP版本、以获得最新特性和功能。要继续使用旧版软件、请执行以下步骤：

. 从 * 卷 * 选项卡中，选择 * 备份设置 * 。
. 在_Backup Settings_页面中，单击*显示先前BlueXP备份和恢复版本*的单选按钮。
+
然后、您可以使用先前版本的软件管理旧集群。





=== 能够创建用于备份到对象存储的存储容器

在对象存储中创建备份文件时、默认情况下、备份和恢复服务会在对象存储中为您创建分段。如果要使用特定名称或分配特殊属性、您可以自行创建分段。如果要创建自己的存储分段、必须在启动激活向导之前创建它。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["了解如何创建对象存储分段"]。

在将备份文件创建备份到StorageGRID系统时、当前不支持此功能。



== 2023年7月4日



=== 增强了适用于应用程序的BlueXP备份和恢复功能(云原生)

* SAP HANA系统
+
** 支持对具有Azure NetApp Files二级保护的非数据卷和全局非数据卷进行连接和副本还原


* Oracle数据库
+
** 支持将Azure NetApp Files上的Oracle数据库还原到备用位置
** 支持在Azure NetApp Files上为Oracle数据库备份编制Oracle恢复管理器(RMAN)目录
** 用于将数据库主机置于维护模式以执行维护任务






=== 针对应用程序的BlueXP备份和恢复增强功能(混合)

* 支持还原到备用位置
* 用于挂载Oracle数据库备份
* 支持将备份从GCP移至归档层




=== 虚拟机BlueXP备份和恢复增强功能(混合)

* 支持保护NFS和VMFS类型的数据存储库
* 允许您取消注册适用于VMware vSphere的SnapCenter插件主机
* 支持刷新和发现最新数据存储库和备份




== 2023年6月5日



=== FlexGroup卷可以使用DataLock和防软件保护进行备份和保护

现在、当集群运行ONTAP 9.13.1或更高版本时、FlexGroup卷的备份策略可以使用DataLock和防软件保护。



=== 新增报告功能

现在、您可以通过报告选项卡生成备份清单报告、其中包括特定帐户、工作环境或SVM清单的所有备份。您还可以创建数据保护作业活动报告、该报告提供有关Snapshot、备份、克隆和还原操作的信息、这些信息有助于您监控服务级别协议。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["关于数据保护覆盖范围的报告"]。



=== 作业监视器增强功能

现在、您可以在"作业监控"页面上将_backup生命周期_作为作业类型进行查看、以帮助您跟踪整个备份生命周期。您还可以在BlueXP时间线上查看所有操作的详细信息。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["监控备份和还原作业的状态"]。



=== 针对不匹配的策略标签的附加通知警报

添加了一个新的备份警报："由于Snapshot策略标签不匹配、未创建备份文件"。如果备份策略中定义的_label_在Snapshot策略中没有匹配的_label_、则不会创建任何备份文件。您需要使用System Manager或ONTAP命令行界面将缺少的标签添加到卷Snapshot策略中。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["查看BlueXP备份和恢复可以发送的所有警报"]。



=== 自动备份非公开站点中的关键BlueXP备份和恢复文件

在无法访问Internet的站点(称为"专用模式"部署)中使用BlueXP备份和恢复时、BlueXP备份和恢复信息仅存储在本地连接器系统上。这一新功能会自动将关键的BlueXP备份和恢复数据备份到已连接StorageGRID系统上的存储分段中、以便您可以在必要时将这些数据恢复到新的连接器上。 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["了解更多信息。"]



== 2023年5月8日



=== 现在、可以从归档存储和锁定的备份执行文件夹级还原操作

如果已为备份文件配置DataLock和防软件保护、或者备份文件驻留在归档存储中、则现在、如果集群运行的是ONTAP 9.13.1或更高版本、则支持文件夹级还原操作。



=== 将卷备份到Google Cloud时、支持跨区域和跨项目客户管理的密钥

现在、您可以选择与客户管理的加密密钥(CMDK)项目不同的项目中的存储分段。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["详细了解如何设置您自己的客户管理加密密钥"](英文)

endif::gcp[]



=== 现在、备份文件支持AWS中国地区

现在、如果集群运行的是ONTAP 9.12.1或更高版本、则支持将AWS中国北京(CN-north-1)和宁夏(CN-north-1)区域作为备份文件的目标。

请注意、分配给BlueXP Connector的IAM策略需要将All _Resource_部分下的AWS资源名称"arn"从"aws"更改为"AAWS CN"；例如"arn：aws-cn：s3：：：NetApp-backup-*"。

ifdef::aws[]

有关详细信息、请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"] 和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["将本地ONTAP数据备份到Amazon S3"] 。

endif::aws[]



=== 作业监控的增强功能

对于运行ONTAP 9.13.1或更高版本的内部ONTAP 系统，系统启动的作业(例如正在进行的备份操作)现在可在*作业监控*选项卡中找到。早期的ONTAP 版本将仅显示用户启动的作业。



== 2023年4月14日



=== 增强了适用于应用程序的BlueXP备份和恢复功能(云原生)

* SAP HANA数据库
+
** 支持基于脚本的系统刷新
** 如果配置了Azure NetApp Files 备份、则支持单文件Snapshot还原
** 支持插件升级


* Oracle数据库
+
** 通过简化非root sudo用户配置增强了插件部署
** 支持插件升级
** 支持对Azure NetApp Files 上的Oracle数据库进行自动发现和策略驱动型保护
** 支持通过粒度恢复将Oracle数据库还原到原始位置






=== 针对应用程序的BlueXP备份和恢复增强功能(混合)

* 适用于应用程序(混合)的BlueXP备份和恢复由SaaS控制平台驱动
* 修改了混合REST API以与云原生API保持一致。
* 支持电子邮件通知




== 2023年4月4日



=== 能够在"受限"模式下将数据从Cloud Volumes ONTAP 系统备份到云

现在、您可以在"受限模式"下从AWS、Azure和GCP商业区域中安装的Cloud Volumes ONTAP 系统备份数据。这要求您首先在"受限"商业区域安装连接器。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["详细了解BlueXP部署模式"^](英文)。

ifdef::aws[]

请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"]

endif::aws[]

ifdef::azure[]

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["将Cloud Volumes ONTAP 数据备份到Azure Blob"]

endif::azure[]



=== 可以使用API将内部ONTAP 卷备份到ONTAP S3

通过API中的新功能、您可以使用BlueXP备份和恢复功能将卷快照备份到ONTAP S3。此功能目前仅适用于内部部署的ONTAP 系统。有关详细说明、请参见博客 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["与ONTAP S3集成作为目标"^]。



=== 可以将Azure存储帐户的分区冗余方面从LRS更改为ZRS

默认情况下、在从Cloud Volumes ONTAP 系统创建到Azure存储的备份时、BlueXP备份和恢复会为Blob容器配置本地冗余(LRS)以实现成本优化。如果要在不同分区之间复制数据、可以将此设置更改为区域冗余(ZRS)。请参见的Microsoft说明 https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["更改存储帐户的复制方式"^]。



=== 作业监控的增强功能

* 对于运行ONTAP 9.13.0或更高版本的Cloud Volumes ONTAP 系统、用户启动的备份和还原操作以及系统启动的作业(如正在进行的备份操作)现在均可在*作业监控*选项卡中找到。早期的ONTAP 版本将仅显示用户启动的作业。
* 除了可以下载CSV文件以报告所有作业之外、现在您还可以下载单个作业的JSON文件并查看其详细信息。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["了解更多信息。"]。
* 添加了两个新的备份作业警报："Scheduled job failure"和"Restore job completes but with warnings"。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["查看BlueXP备份和恢复可以发送的所有警报"]。




== 2023年3月9日



=== 文件夹级别的还原操作现在包括所有子文件夹和文件

过去、在还原文件夹时、只会还原该文件夹中的文件、而不会还原子文件夹或子文件夹中的文件。现在、如果您使用的是ONTAP 9.13.0或更高版本、则会还原选定文件夹中的所有子文件夹和文件。如果顶级文件夹中有多个嵌套文件夹、则可以节省大量时间和资金。



=== 能够从出站连接受限的站点中的Cloud Volumes ONTAP系统备份数据

现在、您可以将数据从AWS和Azure商业区域中安装的Cloud Volumes ONTAP 系统备份到Amazon S3或Azure Blob。这要求您在商业区域的Linux主机上以"受限模式"安装连接器、并在该处部署Cloud Volumes ONTAP系统。

ifdef::aws[]

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"]

endif::aws[]

ifdef::azure[]

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["将Cloud Volumes ONTAP 数据备份到Azure Blob"]

endif::azure[]



=== 对作业监控器进行了多项增强

* "作业监控"页面添加了高级筛选功能、因此您可以按时间、工作负载(卷、应用程序或虚拟机)、作业类型、 状态、工作环境和Storage VM。您还可以输入自由文本来搜索任何资源、例如"application_3"。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["请参见如何使用高级筛选器"](英文)
* 对于运行ONTAP 9.13.0或更高版本的Cloud Volumes ONTAP 系统、用户启动的备份和还原操作以及系统启动的作业(如正在进行的备份操作)现在均可在*作业监控*选项卡中找到。早期版本的Cloud Volumes ONTAP 系统和内部ONTAP 系统此时将仅显示用户启动的作业。




== 2023年2月6日



=== 能够将旧备份文件从StorageGRID 系统移动到Azure归档存储

现在、您可以将旧备份文件从StorageGRID 系统分层到Azure中的归档存储。这样、您就可以释放StorageGRID 系统上的空间、并通过对旧备份文件使用成本低廉的存储类节省资金。

如果您的内部集群使用的是ONTAP 9.12.1或更高版本、而StorageGRID 系统使用的是11.4或更高版本、则可以使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["单击此处了解更多信息"^]。



=== 可以为Azure Blob中的备份文件配置DataLock和勒索软件保护

现在、存储在Azure Blob中的备份文件支持DataLock和勒索软件保护。如果您的Cloud Volumes ONTAP 或内部ONTAP 系统运行的是ONTAP 9.12.1或更高版本、现在您可以锁定备份文件并对其进行扫描、以检测可能的勒索软件。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。



=== 备份和还原FlexGroup 卷增强功能

* 现在、您可以在还原FlexGroup 卷时选择多个聚合。在上一版本中、您只能选择一个聚合。
* 现在、Cloud Volumes ONTAP 系统支持FlexGroup 卷还原。在上一个版本中、您只能还原到内部ONTAP 系统。




=== Cloud Volumes ONTAP 系统可以将较早的备份移动到Google归档存储

备份文件最初是在Google标准存储类中创建的。现在、您可以使用BlueXP备份和恢复功能将旧备份分层到Google Archive存储、以进一步优化成本。上一版本仅在内部ONTAP 集群中支持此功能—现在支持在Google Cloud中部署的Cloud Volumes ONTAP 系统。



=== 现在、您可以通过卷还原操作选择要还原卷数据的SVM

现在、您可以将卷数据还原到ONTAP 集群中的不同Storage VM。过去无法选择Storage VM。



=== 增强了对MetroCluster 配置中卷的支持

现在、如果使用的是ONTAP 9.12.1 GA或更高版本、则在MetroCluster 配置中连接到主系统时、支持备份。整个备份配置将传输到二级系统、以便在切换后自动继续备份到云。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["有关详细信息、请参见备份限制"]。



== 2023年1月9日



=== 能够将旧备份文件从StorageGRID 系统移动到AWS S3归档存储

现在、您可以将旧备份文件从StorageGRID 系统分层到AWS S3中的归档存储。这样、您就可以释放StorageGRID 系统上的空间、并通过对旧备份文件使用成本低廉的存储类节省资金。您可以选择将备份分层到AWS S3 Glacier或S3 Glacier深度归档存储。

如果您的内部集群使用的是ONTAP 9.12.1或更高版本、而StorageGRID 系统使用的是11.3或更高版本、则可以使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["单击此处了解更多信息"]。



=== 可以在Google Cloud上为数据加密选择您自己由客户管理的密钥

将数据从ONTAP 系统备份到Google云存储时、现在您可以在激活向导中选择自己的客户管理的数据加密密钥、而不是使用默认的Google管理的加密密钥。只需先在Google中设置客户管理的加密密钥、然后在激活BlueXP备份和恢复时输入详细信息。



=== 服务帐户不再需要"存储管理员"角色来在Google Cloud Storage中创建备份

在早期版本中、支持BlueXP备份和恢复访问Google Cloud存储分段的服务帐户需要"存储管理员"角色。现在、您可以创建一个自定义角色、并为该服务帐户分配一组经过精简的权限。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["请参见如何准备用于备份的Google Cloud存储"](英文)

endif::gcp[]



=== 增加了对在无法访问Internet的站点中使用搜索和还原还原还原数据的支持

如果您要将数据从内部ONTAP 集群备份到无法访问Internet的站点(也称为非公开站点或脱机站点)中的StorageGRID 、则现在可以根据需要使用搜索和还原选项还原数据。此功能要求在脱机站点中部署BlueXP Connector (3.9.25或更高版本)。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["请参见如何使用搜索和放大器还原ONTAP 数据"]。
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["请参见如何在脱机站点中安装Connector"]。



=== 能够以.csv报告的形式下载作业监控结果页面

筛选"作业监控"页面以显示您感兴趣的作业和操作后、现在可以生成并下载该数据的.csv文件。然后、您可以分析这些信息、或者将报告发送给组织中的其他人员。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["请参见如何生成作业监控报告"]。



== 2022年12月19日



=== Cloud Backup for Applications的增强功能

* SAP HANA数据库
+
** 支持基于策略备份和还原驻留在Azure NetApp Files 上的SAP HANA数据库
** 支持自定义策略


* Oracle数据库
+
** 添加主机并自动部署插件
** 支持自定义策略
** 支持基于策略备份、还原和克隆Cloud Volumes ONTAP 上的Oracle数据库
** 支持基于策略备份和还原驻留在Amazon FSX for NetApp ONTAP 上的Oracle数据库
** 支持使用连接和复制方法还原Oracle数据库
** 支持Oracle 21c
** 支持克隆云原生Oracle数据库






=== 适用于虚拟机的Cloud Backup增强功能

* 虚拟机
+
** 从内部二级存储备份虚拟机
** 支持自定义策略
** 支持Google Cloud Platform (GCP)备份一个或多个数据存储库
** 支持低成本云存储、例如Glacier、Deep Glacier和Azure Archive






== 2022年12月6日



=== 所需的Connector出站Internet访问端点更改

由于Cloud Backup发生了更改、您需要更改以下连接器端点才能成功执行Cloud Backup操作：

[cols="50,50"]
|===
| 旧端点 | 新端点 


| https://cloudmanager.cloud.netapp.com | https://api.bluexp.netapp.com 


| https://*.cloudmanager.cloud.netapp.com | https://*.api.bluexp.netapp.com 
|===
请查看的完整端点列表 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]， https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure 酒店"^] 云环境。



=== 支持在UI中选择Google Archival存储类

备份文件最初是在Google标准存储类中创建的。现在、您可以使用Cloud Backup UI在一定天数后将旧备份分层到Google Archive存储、以便进一步优化成本。

目前、使用ONTAP 9.12.1或更高版本的内部ONTAP 集群支持此功能。目前、此功能不适用于Cloud Volumes ONTAP 系统。



=== 支持FlexGroup 卷

Cloud Backup现在支持备份和还原FlexGroup 卷。使用ONTAP 9.12.1或更高版本时、您可以将FlexGroup 卷备份到公有 和私有云存储。如果您的工作环境包含FlexVol 和FlexGroup 卷、则在更新ONTAP 软件后、您可以备份这些系统上的任何FlexGroup 卷。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["请参见支持的卷类型的完整列表"]。



=== 能够将数据从备份还原到Cloud Volumes ONTAP 系统上的特定聚合

在早期版本中、只有在将数据还原到内部ONTAP 系统时、才能选择聚合。现在、在将数据还原到Cloud Volumes ONTAP 系统时、此功能有效。



== 2022年11月2日



=== 能够将旧Snapshot副本导出到基线备份文件

如果工作环境中的卷具有与备份计划标签匹配的任何本地Snapshot副本(例如、每日、每周等)、则可以将这些历史快照作为备份文件导出到对象存储。这样、您可以通过将旧的Snapshot副本移动到基线备份副本中来初始化云中的备份。

在为您的工作环境激活Cloud Backup时、此选项可用。您也可以稍后在中更改此设置 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["高级设置页面"]。



=== Cloud Backup现在可用于归档源系统上不再需要的卷

现在、您可以删除卷的备份关系。如果您希望停止创建新备份文件并删除源卷、但保留所有现有备份文件、则可以使用此功能提供归档机制。这样、您就可以在将来根据需要从备份文件还原卷、同时从源存储系统中清除空间。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["了解如何操作"]。



=== 添加了通过电子邮件和通知中心接收Cloud Backup警报的支持

Cloud Backup已集成到BlueXP通知服务中。您可以通过单击BlueXP菜单栏中的通知铃来显示Cloud Backup通知。此外、您还可以将BlueXP配置为通过电子邮件发送警报通知、以便即使未登录到系统、您也可以了解重要的系统活动。可以将此电子邮件发送给需要了解备份和还原活动的任何收件人。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["了解如何操作"]。



=== 通过新的高级设置页面、您可以更改集群级别的备份设置

通过此新页面、您可以更改在为每个ONTAP 系统激活Cloud Backup时设置的多个集群级别备份设置。您还可以修改应用为"默认"备份设置的某些设置。您可以更改的一整套备份设置包括：

* 为ONTAP 系统授予访问对象存储权限的存储密钥
* 分配用于将备份上传到对象存储的网络带宽
* 未来卷的自动备份设置(和策略)
* 归档存储类(仅限AWS)
* 初始基线备份文件中是否包含历史Snapshot副本
* 是否从源系统中删除"每年"快照
* 连接到对象存储的ONTAP IP空间(如果激活期间选择不正确)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["了解有关管理集群级别备份设置的更多信息"]。



=== 现在、您可以在使用内部部署连接器时使用搜索和还原来还原备份文件

在先前版本中、增加了在内部部署连接器时向公有 云创建备份文件的支持。在此版本中、我们仍支持在您的内部部署Connector时使用搜索和还原从Amazon S3或Azure Blob还原备份。搜索和还原还支持立即将备份从StorageGRID 系统还原到内部ONTAP 系统。

目前、在使用搜索和还原从Google Cloud Storage还原备份时、必须在Google Cloud Platform中部署Connector。



=== 已更新作业监控页面

已对进行了以下更新 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["作业监控页面"]：

* "工作负载"列可用、因此您可以筛选页面以查看以下备份服务的作业：卷、应用程序和虚拟机。
* 如果要查看特定备份作业的这些详细信息、可以为"用户名"和"作业类型"添加新列。
* "作业详细信息"页面将显示为完成主作业而正在运行的所有子作业。
* 此页面每15分钟自动刷新一次、以便您始终可以看到最新的作业状态结果。您可以单击*刷新*按钮立即更新此页面。




=== AWS跨帐户备份增强功能

如果要对Cloud Volumes ONTAP 备份使用与源卷不同的AWS帐户、则必须在BlueXP中添加目标AWS帐户凭据、并且必须将权限"S3：PutBucketPolicy"和"S3：PutBucketOwnershipControls"添加到为BlueXP提供权限的IAM角色中。过去、您需要在AWS控制台中配置许多设置、而不再需要这样做。



== 2022年9月28日



=== Cloud Backup for Applications的增强功能

* 支持Google Cloud Platform (GCP)和StorageGRID 备份应用程序一致的快照
* 创建自定义策略
* 支持归档存储
* 备份SAP HANA应用程序
* 备份VMware环境中的Oracle和SQL应用程序
* 从内部二级存储备份应用程序
* 停用备份
* 取消注册SnapCenter 服务器




=== 适用于虚拟机的Cloud Backup增强功能

* 支持StorageGRID 备份一个或多个数据存储库
* 创建自定义策略




== 2022年9月19日



=== 可以为StorageGRID 系统中的备份文件配置DataLock和勒索软件保护

上一版本针对存储在Amazon S3存储分段中的备份引入了_DataLock和勒索软件保护_。此版本扩展了对StorageGRID 系统中存储的备份文件的支持。如果集群使用的是ONTAP 9.11.1或更高版本、而StorageGRID 系统运行的是11.6.0.3或更高版本、则可以使用此新的备份策略选项。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。

请注意、您需要运行的Connector软件版本为3.9.22或更高版本。连接器必须安装在您的内部环境中、并且可以安装在可访问Internet或不可访问Internet的站点中。



=== 现在、您可以从备份文件中进行文件夹级还原

现在、如果您需要访问某个备份文件(目录或共享)中的所有文件、则可以从该文件还原该文件夹。与还原整个卷相比、还原文件夹的效率要高得多。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。此时、您只能选择和还原单个文件夹、并且只会还原该文件夹中的文件、而不会还原子文件夹或子文件夹中的文件。



=== 现在、可以从已移至归档存储的备份中进行文件级还原

过去、您只能从已移至归档存储的备份文件还原卷(仅限AWS和Azure)。现在、您可以从这些归档备份文件还原单个文件。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 现在、文件级还原提供了覆盖原始源文件的选项

过去、还原到原始卷的文件始终会作为前缀为"Restore_<file_name>"的新文件进行还原。现在、您可以选择在将源文件还原到卷上的原始位置时覆盖此源文件。此功能可用于使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 拖放以启用云备份到StorageGRID 系统

如果 https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 备份目标作为工作环境存在于Canvas上、您可以将内部ONTAP 工作环境拖动到目标上以启动Cloud Backup设置向导。
