---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: 了解BlueXP备份和恢复的新增功能。 
---
= BlueXP备份和恢复的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP备份和恢复的新增功能。



== 2023年6月5日



=== FlexGroup卷可以使用DataLock和防软件保护进行备份和保护

现在、当集群运行ONTAP 9.13.1或更高版本时、FlexGroup卷的备份策略可以使用DataLock和防软件保护。



=== 新增报告功能

现在、您可以通过报告选项卡生成备份清单报告、其中包括特定帐户、工作环境或SVM清单的所有备份。您还可以创建数据保护作业活动报告、该报告提供有关Snapshot、备份、克隆和还原操作的信息、这些信息有助于您监控服务级别协议。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["关于数据保护覆盖范围的报告"]。



=== 作业监视器增强功能

现在、您可以在"作业监控"页面上将_backup生命周期_作为作业类型进行查看、以帮助您跟踪整个备份生命周期。您还可以在BlueXP时间线上查看所有操作的详细信息。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["监控备份和还原作业的状态"]。



=== 自动备份非公开站点中的关键BlueXP备份和恢复文件

在无法访问Internet的站点(称为"专用模式"部署)中使用BlueXP备份和恢复时、BlueXP备份和恢复信息仅存储在本地连接器系统上。这一新功能会自动将关键的BlueXP备份和恢复数据备份到已连接StorageGRID系统上的存储分段中、以便您可以在必要时将这些数据恢复到新的连接器上。 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["了解更多信息。"]



== 2023年5月8日



=== 现在、可以从归档存储和锁定的备份执行文件夹级还原操作

如果已为备份文件配置DataLock和防软件保护、或者备份文件驻留在归档存储中、则现在、如果集群运行的是ONTAP 9.13.1或更高版本、则支持文件夹级还原操作。



=== 将卷备份到Google Cloud时、支持跨区域和跨项目客户管理的密钥

现在、您可以选择与客户管理的加密密钥(CMDK)项目不同的项目中的存储分段。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["详细了解如何设置您自己的客户管理加密密钥"]。



=== 现在、备份文件支持AWS中国地区

现在、如果集群运行的是ONTAP 9.12.1或更高版本、则支持将AWS中国北京(CN-north-1)和宁夏(CN-north-1)区域作为备份文件的目标。

请注意、分配给BlueXP Connector的IAM策略需要将All _Resource_部分下的AWS资源名称"arn"从"aws"更改为"AAWS CN"；例如"arn：aws-cn：s3：：：NetApp-backup-*"。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"] 和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["将本地ONTAP 数据备份到Amazon S3"] 了解详细信息。



=== 作业监控的增强功能

对于运行ONTAP 9.13.1或更高版本的内部ONTAP 系统，系统启动的作业(例如正在进行的备份操作)现在可在*作业监控*选项卡中找到。早期的ONTAP 版本将仅显示用户启动的作业。



== 2023年4月14日



=== 增强了适用于应用程序的BlueXP备份和恢复功能(云原生)

* SAP HANA数据库
+
** 支持基于脚本的系统刷新
** 如果配置了Azure NetApp Files 备份、则支持单文件Snapshot还原
** 支持插件升级


* Oracle数据库
+
** 通过简化非root sudo用户配置增强了插件部署
** 支持插件升级
** 支持对Azure NetApp Files 上的Oracle数据库进行自动发现和策略驱动型保护
** 支持通过粒度恢复将Oracle数据库还原到原始位置






=== 针对应用程序的BlueXP备份和恢复增强功能(混合)

* 适用于应用程序(混合)的BlueXP备份和恢复由SaaS控制平台驱动
* 修改了混合REST API以与云原生API保持一致。
* 支持电子邮件通知




== 2023年4月4日



=== 能够在"受限"模式下将数据从Cloud Volumes ONTAP 系统备份到云

现在、您可以在"受限模式"下从AWS、Azure和GCP商业区域中安装的Cloud Volumes ONTAP 系统备份数据。这要求您首先在"受限"商业区域安装Connector。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["详细了解BlueXP部署模式"^]。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"] 和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["将Cloud Volumes ONTAP 数据备份到Azure Blob"]。



=== 可以使用API将内部ONTAP 卷备份到ONTAP S3

通过API中的新功能、您可以使用BlueXP备份和恢复功能将卷快照备份到ONTAP S3。此功能目前仅适用于内部部署的ONTAP 系统。有关详细说明、请参见博客 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["与ONTAP S3集成作为目标"^]。



=== 可以将Azure存储帐户的分区冗余方面从LRS更改为ZRS

默认情况下、在从Cloud Volumes ONTAP 系统创建到Azure存储的备份时、BlueXP备份和恢复会为Blob容器配置本地冗余(LRS)以实现成本优化。如果要在不同分区之间复制数据、可以将此设置更改为区域冗余(ZRS)。请参见的Microsoft说明 https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["更改存储帐户的复制方式"^]。



=== 作业监控的增强功能

* 对于运行ONTAP 9.13.0或更高版本的Cloud Volumes ONTAP 系统、用户启动的备份和还原操作以及系统启动的作业(如正在进行的备份操作)现在均可在*作业监控*选项卡中找到。早期的ONTAP 版本将仅显示用户启动的作业。
* 除了可以下载CSV文件以报告所有作业之外、现在您还可以下载单个作业的JSON文件并查看其详细信息。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["了解更多信息。"]。
* 添加了两个新的备份作业警报："Scheduled job failure"和"Restore job completes but with warnings"。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["查看BlueXP备份和恢复可以发送的所有警报"]。




== 2023年3月9日



=== 文件夹级别的还原操作现在包括所有子文件夹和文件

过去、在还原文件夹时、只会还原该文件夹中的文件、而不会还原子文件夹或子文件夹中的文件。现在、如果您使用的是ONTAP 9.13.0或更高版本、则会还原选定文件夹中的所有子文件夹和文件。如果顶级文件夹中有多个嵌套文件夹、则可以节省大量时间和资金。



=== 能够在非公开站点中备份Cloud Volumes ONTAP 系统中的数据

现在、您可以将数据从AWS和Azure商业区域中安装的Cloud Volumes ONTAP 系统备份到Amazon S3或Azure Blob。这要求您在商业区域的Linux主机上安装连接器、并在该主机上部署Cloud Volumes ONTAP 系统。请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["将 Cloud Volumes ONTAP 数据备份到 Amazon S3"] 和 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["将Cloud Volumes ONTAP 数据备份到Azure Blob"]。



=== 对作业监控器进行了多项增强

* 作业监控页面添加了高级筛选功能、因此您可以按时间、工作负载(卷、应用程序、虚拟机或Kubernetes)搜索备份和还原作业。 作业类型、状态、工作环境和Storage VM。您还可以输入自由文本来搜索任何资源、例如"application_3"。  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["请参见如何使用高级筛选器"]。
* 对于运行ONTAP 9.13.0或更高版本的Cloud Volumes ONTAP 系统、用户启动的备份和还原操作以及系统启动的作业(如正在进行的备份操作)现在均可在*作业监控*选项卡中找到。早期版本的Cloud Volumes ONTAP 系统和内部ONTAP 系统此时将仅显示用户启动的作业。




== 2023年2月6日



=== 能够将旧备份文件从StorageGRID 系统移动到Azure归档存储

现在、您可以将旧备份文件从StorageGRID 系统分层到Azure中的归档存储。这样、您就可以释放StorageGRID 系统上的空间、并通过对旧备份文件使用成本低廉的存储类节省资金。

如果您的内部集群使用的是ONTAP 9.12.1或更高版本、而StorageGRID 系统使用的是11.4或更高版本、则可以使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["单击此处了解更多信息"^]。



=== 可以为Azure Blob中的备份文件配置DataLock和勒索软件保护

现在、存储在Azure Blob中的备份文件支持DataLock和勒索软件保护。如果您的Cloud Volumes ONTAP 或内部ONTAP 系统运行的是ONTAP 9.12.1或更高版本、现在您可以锁定备份文件并对其进行扫描、以检测可能的勒索软件。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。



=== 备份和还原FlexGroup 卷增强功能

* 现在、您可以在还原FlexGroup 卷时选择多个聚合。在上一版本中、您只能选择一个聚合。
* 现在、Cloud Volumes ONTAP 系统支持FlexGroup 卷还原。在上一个版本中、您只能还原到内部ONTAP 系统。




=== Cloud Volumes ONTAP 系统可以将较早的备份移动到Google归档存储

备份文件最初是在Google标准存储类中创建的。现在、您可以使用BlueXP备份和恢复功能将旧备份分层到Google Archive存储、以进一步优化成本。上一版本仅在内部ONTAP 集群中支持此功能—现在支持在Google Cloud中部署的Cloud Volumes ONTAP 系统。



=== 现在、您可以通过卷还原操作选择要还原卷数据的SVM

现在、您可以将卷数据还原到ONTAP 集群中的不同Storage VM。过去无法选择Storage VM。



=== 增强了对MetroCluster 配置中卷的支持

现在、如果使用的是ONTAP 9.12.1 GA或更高版本、则在MetroCluster 配置中连接到主系统时、支持备份。整个备份配置将传输到二级系统、以便在切换后自动继续备份到云。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["有关详细信息、请参见备份限制"]。



== 2023年1月9日



=== 能够将旧备份文件从StorageGRID 系统移动到AWS S3归档存储

现在、您可以将旧备份文件从StorageGRID 系统分层到AWS S3中的归档存储。这样、您就可以释放StorageGRID 系统上的空间、并通过对旧备份文件使用成本低廉的存储类节省资金。您可以选择将备份分层到AWS S3 Glacier或S3 Glacier深度归档存储。

如果您的内部集群使用的是ONTAP 9.12.1或更高版本、而StorageGRID 系统使用的是11.3或更高版本、则可以使用此功能。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["单击此处了解更多信息"]。



=== 可以在Google Cloud上为数据加密选择您自己由客户管理的密钥

将数据从ONTAP 系统备份到Google云存储时、现在您可以在激活向导中选择自己的客户管理的数据加密密钥、而不是使用默认的Google管理的加密密钥。只需先在Google中设置客户管理的加密密钥、然后在激活BlueXP备份和恢复时输入详细信息。



=== 服务帐户不再需要"存储管理员"角色来在Google Cloud Storage中创建备份

在早期版本中、支持BlueXP备份和恢复访问Google Cloud存储分段的服务帐户需要"存储管理员"角色。现在、您可以创建一个自定义角色、并为该服务帐户分配一组经过精简的权限。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["请参见如何准备用于备份的Google Cloud存储"]。



=== 增加了对在无法访问Internet的站点中使用搜索和还原还原还原数据的支持

如果您要将数据从内部ONTAP 集群备份到无法访问Internet的站点(也称为非公开站点或脱机站点)中的StorageGRID 、则现在可以根据需要使用搜索和还原选项还原数据。此功能要求在脱机站点中部署BlueXP Connector (3.9.25或更高版本)。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["请参见如何使用搜索和放大器还原ONTAP 数据"]。
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["请参见如何在脱机站点中安装Connector"]。



=== 能够以.csv报告的形式下载作业监控结果页面

筛选"作业监控"页面以显示您感兴趣的作业和操作后、现在可以生成并下载该数据的.csv文件。然后、您可以分析这些信息、或者将报告发送给组织中的其他人员。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["请参见如何生成作业监控报告"]。



== 2022年12月19日



=== Cloud Backup for Applications的增强功能

* SAP HANA数据库
+
** 支持基于策略备份和还原驻留在Azure NetApp Files 上的SAP HANA数据库
** 支持自定义策略


* Oracle数据库
+
** 添加主机并自动部署插件
** 支持自定义策略
** 支持基于策略备份、还原和克隆Cloud Volumes ONTAP 上的Oracle数据库
** 支持基于策略备份和还原驻留在Amazon FSX for NetApp ONTAP 上的Oracle数据库
** 支持使用连接和复制方法还原Oracle数据库
** 支持Oracle 21c
** 支持克隆云原生Oracle数据库






=== 适用于虚拟机的Cloud Backup增强功能

* 虚拟机
+
** 从内部二级存储备份虚拟机
** 支持自定义策略
** 支持Google Cloud Platform (GCP)备份一个或多个数据存储库
** 支持低成本云存储、例如Glacier、Deep Glacier和Azure Archive






== 2022年12月6日



=== 所需的Connector出站Internet访问端点更改

由于Cloud Backup发生了更改、您需要更改以下连接器端点才能成功执行Cloud Backup操作：

[cols="50,50"]
|===
| 旧端点 | 新端点 


| https://cloudmanager.cloud.netapp.com | https://api.bluexp.netapp.com 


| https://*.cloudmanager.cloud.netapp.com | https://*.api.bluexp.netapp.com 
|===
请查看的完整端点列表 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]， https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure 酒店"^] 云环境。



=== 支持在UI中选择Google Archival存储类

备份文件最初是在Google标准存储类中创建的。现在、您可以使用Cloud Backup UI在一定天数后将旧备份分层到Google Archive存储、以便进一步优化成本。

目前、使用ONTAP 9.12.1或更高版本的内部ONTAP 集群支持此功能。目前、此功能不适用于Cloud Volumes ONTAP 系统。



=== 支持FlexGroup 卷

Cloud Backup现在支持备份和还原FlexGroup 卷。使用ONTAP 9.12.1或更高版本时、您可以将FlexGroup 卷备份到公有 和私有云存储。如果您的工作环境包含FlexVol 和FlexGroup 卷、则在更新ONTAP 软件后、您可以备份这些系统上的任何FlexGroup 卷。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["请参见支持的卷类型的完整列表"]。



=== 能够将数据从备份还原到Cloud Volumes ONTAP 系统上的特定聚合

在早期版本中、只有在将数据还原到内部ONTAP 系统时、才能选择聚合。现在、在将数据还原到Cloud Volumes ONTAP 系统时、此功能有效。



== 2022年11月2日



=== 能够将旧Snapshot副本导出到基线备份文件

如果工作环境中的卷具有与备份计划标签匹配的任何本地Snapshot副本(例如、每日、每周等)、则可以将这些历史快照作为备份文件导出到对象存储。这样、您可以通过将旧的Snapshot副本移动到基线备份副本中来初始化云中的备份。

在为您的工作环境激活Cloud Backup时、此选项可用。您也可以稍后在中更改此设置 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["高级设置页面"]。



=== Cloud Backup现在可用于归档源系统上不再需要的卷

现在、您可以删除卷的备份关系。如果您希望停止创建新备份文件并删除源卷、但保留所有现有备份文件、则可以使用此功能提供归档机制。这样、您就可以在将来根据需要从备份文件还原卷、同时从源存储系统中清除空间。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["了解如何操作"]。



=== 添加了通过电子邮件和通知中心接收Cloud Backup警报的支持

Cloud Backup已集成到BlueXP通知服务中。您可以通过单击BlueXP菜单栏中的通知铃来显示Cloud Backup通知。此外、您还可以将BlueXP配置为通过电子邮件发送警报通知、以便即使未登录到系统、您也可以了解重要的系统活动。可以将此电子邮件发送给需要了解备份和还原活动的任何收件人。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["了解如何操作"]。



=== 通过新的高级设置页面、您可以更改集群级别的备份设置

通过此新页面、您可以更改在为每个ONTAP 系统激活Cloud Backup时设置的多个集群级别备份设置。您还可以修改应用为"默认"备份设置的某些设置。您可以更改的一整套备份设置包括：

* 为ONTAP 系统授予访问对象存储权限的存储密钥
* 分配用于将备份上传到对象存储的网络带宽
* 未来卷的自动备份设置(和策略)
* 归档存储类(仅限AWS)
* 初始基线备份文件中是否包含历史Snapshot副本
* 是否从源系统中删除"每年"快照
* 连接到对象存储的ONTAP IP空间(如果激活期间选择不正确)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["了解有关管理集群级别备份设置的更多信息"]。



=== 现在、您可以在使用内部部署连接器时使用搜索和还原来还原备份文件

在先前版本中、增加了在内部部署连接器时向公有 云创建备份文件的支持。在此版本中、我们仍支持在您的内部部署Connector时使用搜索和还原从Amazon S3或Azure Blob还原备份。搜索和还原还支持立即将备份从StorageGRID 系统还原到内部ONTAP 系统。

目前、在使用搜索和还原从Google Cloud Storage还原备份时、必须在Google Cloud Platform中部署Connector。



=== 已更新作业监控页面

已对进行了以下更新 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["作业监控页面"]：

* 您可以使用"workload"列筛选页面以查看以下备份服务的作业：卷、应用程序、虚拟机和Kubernetes。
* 如果要查看特定备份作业的这些详细信息、可以为"用户名"和"作业类型"添加新列。
* "作业详细信息"页面将显示为完成主作业而正在运行的所有子作业。
* 此页面每15分钟自动刷新一次、以便您始终可以看到最新的作业状态结果。您可以单击*刷新*按钮立即更新此页面。




=== AWS跨帐户备份增强功能

如果要对Cloud Volumes ONTAP 备份使用与源卷不同的AWS帐户、则必须在BlueXP中添加目标AWS帐户凭据、并且必须将权限"S3：PutBucketPolicy"和"S3：PutBucketOwnershipControls"添加到为BlueXP提供权限的IAM角色中。过去、您需要在AWS控制台中配置许多设置、而不再需要这样做。



== 2022年9月28日



=== Cloud Backup for Applications的增强功能

* 支持Google Cloud Platform (GCP)和StorageGRID 备份应用程序一致的快照
* 创建自定义策略
* 支持归档存储
* 备份SAP HANA应用程序
* 备份VMware环境中的Oracle和SQL应用程序
* 从内部二级存储备份应用程序
* 停用备份
* 取消注册SnapCenter 服务器




=== 适用于虚拟机的Cloud Backup增强功能

* 支持StorageGRID 备份一个或多个数据存储库
* 创建自定义策略




== 2022年9月19日



=== 可以为StorageGRID 系统中的备份文件配置DataLock和勒索软件保护

上一版本针对存储在Amazon S3存储分段中的备份引入了_DataLock和勒索软件保护_。此版本扩展了对StorageGRID 系统中存储的备份文件的支持。如果集群使用的是ONTAP 9.11.1或更高版本、而StorageGRID 系统运行的是11.6.0.3或更高版本、则可以使用此新的备份策略选项。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。

请注意、您需要运行的Connector软件版本为3.9.22或更高版本。连接器必须安装在您的内部环境中、并且可以安装在可访问Internet或不可访问Internet的站点中。



=== 现在、您可以从备份文件中进行文件夹级还原

现在、如果您需要访问某个备份文件(目录或共享)中的所有文件、则可以从该文件还原该文件夹。与还原整个卷相比、还原文件夹的效率要高得多。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。此时、您只能选择和还原单个文件夹、并且只会还原该文件夹中的文件、而不会还原子文件夹或子文件夹中的文件。



=== 现在、可以从已移至归档存储的备份中进行文件级还原

过去、您只能从已移至归档存储的备份文件还原卷(仅限AWS和Azure)。现在、您可以从这些归档备份文件还原单个文件。在使用ONTAP 9.11.1或更高版本时、可以使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 现在、文件级还原提供了覆盖原始源文件的选项

过去、还原到原始卷的文件始终会作为前缀为"Restore_<file_name>"的新文件进行还原。现在、您可以选择在将源文件还原到卷上的原始位置时覆盖此源文件。此功能可用于使用浏览和还原方法以及搜索和还原方法执行还原操作。



=== 拖放以启用云备份到StorageGRID 系统

如果 https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] 备份目标作为工作环境存在于Canvas上、您可以将内部ONTAP 工作环境拖动到目标上以启动Cloud Backup设置向导。



== 2022年8月18日



=== 增加了对云原生应用程序数据的保护支持

Cloud Backup for Applications是一种基于SaaS的服务、可为在NetApp Cloud Storage上运行的应用程序提供数据保护功能。在BlueXP中启用的适用于应用程序的云备份可为驻留在Amazon FSX for NetApp ONTAP 上的Oracle数据库提供高效、一致且基于策略的备份和还原。
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-cloud-app-data-to-cloud.html["了解更多信息。"^]。



=== 现在、Azure Blob中的备份文件支持搜索和还原

现在、将备份文件存储在Azure Blob存储中的用户可以使用"搜索和还原"方法还原卷和文件。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#prerequisites-2["请参见如何使用搜索和放大器还原卷和文件"^]。

请注意、要使用此功能、需要在Connector角色中添加其他权限。使用3.9.21版软件(2022年8月)部署的Connector包含这些权限。如果您使用早期版本部署了Connector、则需要手动添加权限。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["如有必要、请参见如何添加这些权限"^]。



=== 我们增加了保护备份文件免遭删除和勒索软件攻击的功能

Cloud Backup现在支持对象锁定、用于进行勒索软件安全备份。如果您的集群使用的是ONTAP 9.11.1或更高版本、而您的备份目标是Amazon S3、则现在可以使用一个名为_DataLock和勒索软件保护_的新备份策略选项。DataLock可防止您的备份文件被修改或删除、勒索软件保护功能会扫描您的备份文件、以查找您的备份文件遭到勒索软件攻击的证据。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["详细了解如何使用DataLock和勒索软件保护来保护备份"^]。

请注意、要使用此功能、需要在Connector角色中添加其他权限。使用3.9.21版软件部署的Connector包含这些权限。如果您使用早期版本部署了Connector、则需要手动添加权限。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions["如有必要、请参见如何添加这些权限"^]。



=== Cloud Backup现在支持使用自定义SnapMirror标签创建的策略

以前、Cloud Backup仅支持预定义的SnapMirror标签、例如每小时、每天、每周、每小时和每年。现在、Cloud Backup可以发现包含您使用System Manager或CLI创建的自定义SnapMirror标签的SnapMirror策略。这些新标签会显示在Cloud Backup UI中、您可以使用所选的SnapMirror标签将卷备份到云中。



=== 对ONTAP 系统的备份策略进行了更多改进

某些备份策略页面经过重新设计、可以更轻松地查看每个ONTAP 集群中的卷可用的所有备份策略。这样可以更轻松地查看可用策略的详细信息、以便您可以在卷上应用最佳策略。



=== 拖放以启用Cloud Backup to Azure Blob和Google Cloud Storage

如果 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-azure-blob.html["Azure Blob"^] 或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-gcp-storage.html["Google Cloud 存储"^] 备份目标作为工作环境存在于Canvas上、您可以将本地ONTAP 或Cloud Volumes ONTAP 工作环境(安装在Azure或GCP中)拖动到目标上以启动备份设置向导。

Amazon S3存储分段已具有此功能。



== 2022年7月13日



=== 添加了对备份SnapLock 企业卷的支持

现在、您可以使用云备份将SnapLock 企业卷备份到公有 和私有云。此功能要求您的ONTAP 系统运行的是ONTAP 9.11.1或更高版本。但是、目前不支持SnapLock 合规性卷。



=== 现在、您可以在使用内部部署连接器时在公有 云中创建备份文件

过去、您需要将Connector部署在与创建备份文件相同的云提供商中。现在、您可以使用内部部署的Connector创建备份文件、将本地ONTAP 系统备份到Amazon S3、Azure Blob和Google云存储。(在StorageGRID 系统上创建备份文件时、始终需要使用内部连接器。)



=== 在为ONTAP 系统创建备份策略时、还可以使用其他功能

* 现在可以按年计划进行备份。对于年度备份、默认保留值为1、但如果要访问前几年的许多备份文件、您可以更改此值。
* 您可以为备份策略命名、以便使用更具描述性的文本来标识策略。




== 2022年6月14日



=== 增加了对在无法访问Internet的站点中备份内部ONTAP 集群数据的支持

如果您的内部ONTAP 集群位于无法访问Internet的站点中、也称为非公开站点或脱机站点、则现在您可以使用Cloud Backup将卷数据备份到同一站点中的NetApp StorageGRID 系统。此功能还要求在脱机站点中部署BlueXP Connector (3.9.19或更高版本)。

https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["请参见如何在脱机站点中安装Connector"]。
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html["了解如何将ONTAP 数据备份到脱机站点中的StorageGRID"]。



=== 适用于虚拟机的Cloud Backup 1.1.0现已正式上市

您可以通过将适用于VMware vSphere的SnapCenter 插件与BlueXP集成来保护虚拟机上的数据。您可以将数据存储库备份到云、并将虚拟机轻松还原回适用于VMware vSphere的内部部署SnapCenter 插件。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-vm-data.html["了解有关保护虚拟机到云的更多信息"]。



=== ONTAP 浏览和还原功能不需要云还原实例

以前从S3和Blob存储执行文件级浏览和还原操作需要一个单独的Cloud Restore实例/虚拟机。此实例在不使用时关闭、但在还原文件时仍会增加一些时间和成本。此功能已被一个免费容器所取代、此容器可在需要时部署在Connector上。它具有以下优势：

* 文件级还原操作不会增加成本
* 文件级还原操作速度更快
* 支持在内部安装Connector时从云中对文件执行浏览和还原操作


请注意、如果您先前使用了Cloud Restore实例/VM、则该实例/VM将自动删除。Cloud Backup进程将每天运行一次、以删除所有旧的Cloud Restore实例。此更改是完全透明的—不会对数据产生任何影响、您也不会注意到备份或还原作业发生了任何更改。



=== 浏览并还原对Google Cloud和StorageGRID 存储中文件的支持

现在、通过添加用于浏览和还原操作的容器(如上所述)、可以从存储在Google Cloud和StorageGRID 系统中的备份文件执行文件还原操作。现在、浏览和还原可用于在所有公有 云提供商之间以及从StorageGRID 还原文件。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["请参见如何使用浏览和放大功能；还原ONTAP 备份中的卷和文件"]。



=== 拖放以启用Cloud Backup到S3存储

如果用于备份的Amazon S3目标作为工作环境存在于Canvas上、则可以将本地ONTAP 集群或Cloud Volumes ONTAP 系统(安装在AWS中)拖动到Amazon S3工作环境中以启动设置向导。



=== 自动将备份策略应用于Kubernetes集群中新创建的卷

如果您在激活Cloud Backup后向Kubernetes集群添加了新的永久性卷、则在过去、您需要记住为这些卷配置备份。现在、您可以选择将自动应用于新创建的卷的策略 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["从_Backup Settings_页面"] 适用于已激活Cloud Backup的集群。



=== Cloud Backup API现在可用于管理备份和还原操作

这些API可从获取 https://docs.netapp.com/us-en/bluexp-automation/cbs/overview.html[]。请参见 link:api-backup-restore.html["此页面"] 有关API的概述。
