= 索引目录支持更新
:allow-uri-read: 




=== 索引目录支持更新

2025 年 2 月，我们推出了更新的索引功能（索引目录 v2），您可以在“搜索和还原”数据还原方法中使用此功能。上一版本显著提升了本地环境中的数据索引性能。在此版本中，索引目录现已可在 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 环境中使用。

如果您是新客户，所有新环境均默认启用索引目录 v2。如果您是现有客户，您可以重新索引您的环境以利用索引目录 v2。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。执行搜索和恢复时，选择“*启用索引*”选项。

索引目录可以跟踪每个卷和备份文件，使您的搜索快速而高效。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜索和恢复来恢复ONTAP数据()"]。



=== Azure 专用链接终结点和服务终结点

通常，BlueXP 备份和恢复会与云提供商建立私有端点，以处理各种保护任务。此版本引入了一项可选设置，可让您启用或禁用 BlueXP 备份和恢复自动创建私有端点的功能。如果您希望更好地控制私有端点的创建过程，这项设置可能会对您有所帮助。

如果禁用此设置，则必须手动创建专用端点，以确保 BlueXP 备份和恢复功能正常运行。如果没有正确的连接，您可能无法成功执行备份和恢复任务。



=== ONTAP S3 上支持 SnapMirror 到云重新同步

上一版本引入了对 SnapMirror 到云重新同步 (SM-C Resync) 的支持。该功能简化了 NetApp 环境中卷迁移期间的数据保护。此版本增加了对 ONTAP S3 以及其他兼容 S3 的提供商（例如 Wasabi 和 MinIO）上的 SM-C Resync 的支持。



=== 为 StorageGRID 带来您自己的存储桶

当您在对象存储中为工作环境创建备份文件时，BlueXP 备份和恢复功能会默认在您配置的对象存储帐户中为备份文件创建容器（存储桶或存储帐户）。之前，您可以覆盖此设置，并为 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。在此版本中，您现在可以自带 StorageGRID 对象存储容器。

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["创建您自己的对象存储容器"]
