= 高性能索引编制
:allow-uri-read: 




=== 高性能索引编制

BlueXP  备份和恢复引入了一项经过更新的索引编制功能、可提高源工作环境中数据的索引编制效率。新的索引编制功能包括更新用户界面、提高搜索和还原数据方法的性能、升级全局搜索功能以及更好的可扩展性。

以下是改进的细分：

* *文件夹整合*：更新后的版本使用包含特定标识符的名称将文件夹分组在一起，使索引编制过程更顺畅。
* *镶木地板文件缩减*：更新后的版本减少了为每个卷编制索引所使用的文件数量，从而简化了流程，并且不再需要额外的数据库。
* *通过更多会话实现横向扩展*：新版本增加了更多会话来处理索引编制任务、从而加快了处理速度。
* *支持多个索引容器*：新版本使用多个容器来更好地管理和分发索引任务。
* *拆分索引工作流*：新版本将索引编制过程分为两部分，提高了效率。
* *改进的并发性*：新版本可以同时删除或移动目录，从而加快索引编制过程。


.谁可以从该功能中受益？
所有新客户均可使用新的索引功能。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。这样、索引目录就可以跟踪每个卷和每个备份文件、从而使搜索快速高效。

在执行搜索和还原时、通过选择"启用索引"选项、在源工作环境中启用索引。

有关详细信息，请参见文档 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜索和恢复来恢复ONTAP数据()"]。

.支持的扩展
新的索引编制功能支持以下功能：

* 不到3分钟即可实现全局搜索效率
* 最多50亿个文件
* 每个集群最多5000个卷
* 每个卷最多10万个快照
* 基线索引编制的最长时间不超过7天。实际时间因环境而异。




=== 全局搜索性能改进

此版本还对全局搜索性能进行了增强。现在、您将看到进度指示器和更详细的搜索结果、包括文件计数和搜索所用时间。用于搜索和索引编制的专用容器可确保在五分钟内完成全局搜索。

请注意以下与全局搜索相关的注意事项：

* 不会对标记为每小时的快照执行新索引。
* 新的索引编制功能仅适用于FlexVol上的快照、不适用于FlexGroup上的快照。

